-- ─────────────────────────────────────────────────────────────────────────────
-- avisos_equipo — registro de los avisos que el bot le manda al EQUIPO por
-- WhatsApp (solicitudes de retiro con botones, escalamientos, relays de ETA).
--
-- Nace del incidente del 11-08-2026: la cuenta de WhatsApp quedó bloqueada por
-- un problema con el método de pago (error 141006 de Meta) y durante DÍAS los
-- avisos al equipo no se entregaron. Nadie se enteró porque Meta ACEPTA el envío
-- (200 + message_id) y recién ~10 s después reporta `failed` por webhook — y ese
-- webhook no tenía dónde escribir el resultado de un aviso, así que se descartaba
-- y el sistema los daba por enviados.
--
-- Con esta tabla el estado real queda registrado: al llegar el `failed` se
-- reintenta por plantilla y, si tampoco sale, se avisa POR CORREO (que es otro
-- proveedor y funciona justo cuando WhatsApp no).
--
-- ⚠️ Correr ANTES de desplegar: en Postgres `ensureSheet` es no-op.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists "avisos_equipo" (
  "id" bigint generated by default as identity primary key,
  "numero" text not null default '',
  -- retiro | operativo
  "tipo" text not null default '',
  -- Texto legible del aviso: es lo que se reenvía por correo si WhatsApp falla.
  "cuerpo" text not null default '',
  "provider_message_id" text not null default '',
  -- enviado (aceptado por Meta, sin falla reportada) | fallido | reintentado |
  -- sin_entregar (falló también el reintento → se avisó por correo)
  "estado" text not null default 'enviado',
  "error" text not null default '',
  -- JSON con lo necesario para reintentar por plantilla: {plantilla, vars, payloads}.
  -- Vacío = se reintenta con la plantilla genérica `aviso_operativo` y el cuerpo.
  "reintento_json" text not null default '',
  -- TRUE si esta fila YA es un reintento (no se reintenta dos veces).
  "es_reintento" text not null default 'FALSE',
  "fecha_creacion" text not null default '',
  "fecha_estado" text not null default ''
);
alter table "avisos_equipo" enable row level security;
create index if not exists "avisos_equipo_provider_idx" on "avisos_equipo" ("provider_message_id");
create index if not exists "avisos_equipo_estado_idx" on "avisos_equipo" ("estado");

notify pgrst, 'reload schema';
