-- ═══════════════════════════════════════════════════════════════════════════
-- Comisiones de convenio  (Configuración → Descuentos Convenios)
-- Correr en el SQL editor de Supabase «Alma Animal» (ixqharypfqlooogoctdp).
-- Idempotente: se puede re-ejecutar sin romper nada.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Modelo: a ciertos veterinarios NO les facturamos el servicio — le emitimos la
-- BOLETA al tutor por el precio completo (por eso su tabla de precios especiales
-- se deja igual a la general) y al vet le queda una COMISIÓN devengada por la
-- derivación. Esa comisión se acumula como saldo y NO toca el EERR hasta que el
-- dueño la salda a mano ("Ajustar saldo"), momento en que se registra el pago
-- como COSTO DE VENTA en eerr_gastos_manuales.

-- ── 1) Regla por veterinaria (una sola vigente por vet) ──────────────────────
create table if not exists "comisiones_reglas" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "tipo" text not null default 'fijo',     -- 'fijo' (CLP) | 'variable' (% sobre la cremación)
  "valor" text not null default '0',
  "activo" text not null default 'TRUE',
  "fecha_creacion" text not null default ''
);
create unique index if not exists "comisiones_reglas_vet_idx" on "comisiones_reglas" ("veterinaria_id");
alter table "comisiones_reglas" enable row level security;

-- ── 2) Devengo: una comisión por ficha boleteada ─────────────────────────────
-- `cliente_id` es ÚNICO: una ficha nunca devenga dos veces. Si la boleta se
-- anula, la fila pasa a estado 'anulada' (no se borra); si se re-emite, la misma
-- fila vuelve a 'devengada' con el nuevo documento.
create table if not exists "comisiones" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "cliente_id" text not null default '',
  "documento_id" text not null default '',  -- boleta (39) que la originó
  "base_monto" text not null default '0',   -- precio de la cremación sobre el que se calculó
  "tipo" text not null default '',          -- copia de la regla al momento del devengo
  "valor" text not null default '0',
  "monto" text not null default '0',
  "estado" text not null default 'devengada', -- 'devengada' | 'anulada'
  "fecha_devengo" text not null default '',
  "fecha_creacion" text not null default ''
);
create unique index if not exists "comisiones_cliente_idx" on "comisiones" ("cliente_id");
create index if not exists "comisiones_vet_idx" on "comisiones" ("veterinaria_id");
alter table "comisiones" enable row level security;

-- ── 3) Ajustes de saldo (lo que se le paga al vet) ───────────────────────────
-- Cada ajuste descuenta del saldo y deja su contrapartida en eerr_gastos_manuales
-- (partida de tipo 'costo') — ese es el único momento en que la comisión golpea
-- el Estado de Resultados.
create table if not exists "comisiones_ajustes" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "monto" text not null default '0',
  "detalle" text not null default '',
  "fecha" text not null default '',
  "cliente_id" text not null default '',
  "gasto_manual_id" text not null default '',
  "creado_por_id" text not null default '',
  "creado_por_nombre" text not null default '',
  "fecha_creacion" text not null default ''
);
create index if not exists "comisiones_ajustes_vet_idx" on "comisiones_ajustes" ("veterinaria_id");
-- Idempotente para bases ya creadas (ver supabase/comisiones-canje-ficha.sql).
alter table "comisiones_ajustes" add column if not exists "cliente_id" text not null default '';
create index if not exists "comisiones_ajustes_cliente_idx" on "comisiones_ajustes" ("cliente_id");
alter table "comisiones_ajustes" enable row level security;

-- ── 4) Partida de costo donde caen los ajustes ───────────────────────────────
-- Si ya existe una partida con ese nombre, el insert no hace nada (unique
-- (tipo, nombre)). La app igual la crea sola si falta.
insert into "eerr_partidas" ("tipo", "nombre", "clave", "orden", "activo", "fecha_creacion")
values ('costo', 'Comisiones convenios', 'comisiones_convenios', '90', 'TRUE', to_char(now(), 'YYYY-MM-DD'))
on conflict ("tipo", "nombre") do nothing;

notify pgrst, 'reload schema';
