-- ─────────────────────────────────────────────────────────────────────────────
-- Subgrupos del EERR: agrupan partidas dentro de un tipo (ingreso/costo/gasto/impuesto).
-- Ej. dentro de Costos: subgrupo "Petróleo" con las partidas "Petróleo Horno" y
-- "Petróleo Vehículo". En el EERR cada subgrupo muestra su subtotal.
-- Correr en el SQL editor de Supabase «Alma Animal» (SUPABASE_URL). Idempotente.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists "eerr_subgrupos" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',          -- ingreso | costo | gasto | impuesto
  "nombre" text not null default '',
  "orden" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_subgrupos_tipo_nombre_uniq" unique ("tipo", "nombre")
);
alter table "eerr_subgrupos" enable row level security;

-- Las partidas pueden pertenecer a un subgrupo (vacío = van directo bajo el tipo).
alter table "eerr_partidas" add column if not exists "subgrupo_id" text not null default '';

notify pgrst, 'reload schema';
