-- ─────────────────────────────────────────────────────────────────────────────
-- Módulo "Estado de Resultados" (EERR) — solo admin general.
-- Correr en el SQL editor del proyecto Supabase «Alma Animal» (SUPABASE_URL).
-- Idempotente: CREATE/ADD COLUMN IF NOT EXISTS, seeds con ON CONFLICT DO NOTHING.
-- Columnas en text (como el resto del esquema); id identity (compatible con next_id).
-- ─────────────────────────────────────────────────────────────────────────────

-- 1) PARTIDAS (Parámetros §3) — líneas del EERR por tipo.
--    tipo: ingreso | costo | gasto | impuesto
--    clave: para las partidas de INGRESO (calculadas desde las ventas):
--           general | convenio | adicionales | eutanasias. Vacía en costo/gasto/impuesto.
create table if not exists "eerr_partidas" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',
  "nombre" text not null default '',
  "clave" text not null default '',
  "orden" text not null default '',
  "activo" text not null default 'TRUE',
  "fecha_creacion" text not null default '',
  constraint "eerr_partidas_tipo_nombre_uniq" unique ("tipo", "nombre")
);
alter table "eerr_partidas" enable row level security;

-- 2) PROVEEDORES (§4) — para la contabilización automática por proveedor.
create table if not exists "eerr_proveedores" (
  "id" bigint generated by default as identity primary key,
  "rut" text not null default '',
  "razon_social" text not null default '',
  "auto_contabiliza" text not null default 'FALSE',
  "auto_tipo" text not null default '',          -- costo | gasto | impuesto
  "auto_partida_id" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_proveedores_rut_uniq" unique ("rut")
);
alter table "eerr_proveedores" enable row level security;

-- 3) GASTOS SII (§2.1) — facturas descargadas del SII (hoy carga manual de CSV).
--    Dedup: (rut, tipo_doc, folio). neto del gasto = monto_neto + monto_exento.
--    contabilizado = TRUE cuando tiene partida asignada.
create table if not exists "eerr_gastos_sii" (
  "id" bigint generated by default as identity primary key,
  "tipo_doc" text not null default '',           -- 33 afecta, 34 exenta, 61 NC, ...
  "tipo_compra" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "folio" text not null default '',
  "fecha_documento" text not null default '',    -- emisión (ISO) — define el mes
  "fecha_recepcion" text not null default '',
  "monto_exento" text not null default '',
  "monto_neto" text not null default '',
  "monto_iva" text not null default '',
  "monto_total" text not null default '',
  "valor_otro_impuesto" text not null default '',
  "comentario" text not null default '',
  "tipo_asignacion" text not null default '',    -- '' | costo | gasto | impuesto
  "partida_id" text not null default '',
  "contabilizado" text not null default 'FALSE',
  "fecha_carga" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_gastos_sii_dedup_uniq" unique ("rut", "tipo_doc", "folio")
);
alter table "eerr_gastos_sii" enable row level security;
create index if not exists "eerr_gastos_sii_fecha_idx" on "eerr_gastos_sii" ("fecha_documento");
create index if not exists "eerr_gastos_sii_partida_idx" on "eerr_gastos_sii" ("partida_id");

-- 4) GASTOS MANUALES (§2.2) — gastos sin factura (todo neto).
create table if not exists "eerr_gastos_manuales" (
  "id" bigint generated by default as identity primary key,
  "tipo_asignacion" text not null default '',    -- costo | gasto | impuesto
  "partida_id" text not null default '',
  "detalle" text not null default '',
  "monto" text not null default '',              -- neto
  "fecha" text not null default '',              -- ISO — define el mes
  "fecha_creacion" text not null default '',
  constraint "eerr_gastos_manuales_partida_check" check (true)
);
alter table "eerr_gastos_manuales" enable row level security;
create index if not exists "eerr_gastos_manuales_fecha_idx" on "eerr_gastos_manuales" ("fecha");

-- 5) RENDICIONES — partida para las que son con BOLETA (las de factura/préstamo no
--    se asignan). tipo_documento ya existe (boleta|factura|prestamo, a nivel app).
alter table "rendiciones"
  add column if not exists "partida_id" text not null default '';

-- ── Seed de partidas (estructura del Excel del EERR) ─────────────────────────
insert into "eerr_partidas" ("tipo", "nombre", "clave", "orden", "activo", "fecha_creacion") values
  ('ingreso',  'General',                 'general',     '1', 'TRUE', ''),
  ('ingreso',  'Convenios (Veterinarios)','convenio',    '2', 'TRUE', ''),
  ('ingreso',  'Adicionales',             'adicionales', '3', 'TRUE', ''),
  ('ingreso',  'Eutanasias',              'eutanasias',  '4', 'TRUE', ''),
  ('costo',    'Petróleo Horno',          '',            '1', 'TRUE', ''),
  ('costo',    'Petróleo Vehículo',       '',            '2', 'TRUE', ''),
  ('costo',    'Ánforas',                 '',            '3', 'TRUE', ''),
  ('costo',    'Otros',                   '',            '4', 'TRUE', ''),
  ('gasto',    'Personal',                '',            '1', 'TRUE', ''),
  ('gasto',    'Arriendo',                '',            '2', 'TRUE', ''),
  ('gasto',    'Arreglos y Mantenciones', '',            '3', 'TRUE', ''),
  ('gasto',    'Gasto financiero',        '',            '4', 'TRUE', ''),
  ('gasto',    'Artículos de Oficina',    '',            '5', 'TRUE', ''),
  ('impuesto', 'Impuestos y Otros',       '',            '1', 'TRUE', '')
on conflict ("tipo", "nombre") do nothing;

-- Recalcular el sequence de id de las tablas nuevas (por si el seed avanzó).
select reset_id_seq('eerr_partidas');

notify pgrst, 'reload schema';
