-- ─────────────────────────────────────────────────────────────────────────────
-- Ventas POS (Facturación) — 2026-08-04
--
-- CORRER ESTO EN SUPABASE «Alma Animal» (SQL editor) ANTES DE DESPLEGAR.
-- En Postgres `ensureColumns` es no-op, así que /api/init-sheets NO crea nada:
-- sin este ALTER, guardar una ficha nueva falla con
-- «Could not find the 'fecha_pago' column ... in the schema cache».
--
-- Es idempotente: se puede correr las veces que sea.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Fecha en que se cobró la venta. La ficha guardaba la forma de pago y el
--    estado, pero no CUÁNDO se pagó: sin eso no se puede armar el día de POS ni
--    cuadrar el abono de Haulmer (que llega al día hábil siguiente).
alter table "clientes" add column if not exists "fecha_pago" text not null default '';

-- 2. Comisión del procesador de pagos (TUU/Haulmer). Fila única id=1, editable
--    desde Facturación → Ventas POS. Valores de arranque = contrato vigente a
--    ago-2026: $65 por transacción + 0,79% del total cobrado, ambos netos,
--    más 19% de IVA sobre esa comisión.
create table if not exists "config_pos" (
  "id" bigint generated by default as identity primary key,
  "comision_fija" text not null default '65',
  "comision_variable" text not null default '0.79',
  "iva" text not null default '19',
  "fecha_actualizacion" text not null default ''
);

insert into "config_pos" ("id", "comision_fija", "comision_variable", "iva")
select 1, '65', '0.79', '19'
where not exists (select 1 from "config_pos");

-- La secuencia queda alineada con el id sembrado a mano.
select setval(pg_get_serial_sequence('config_pos', 'id'), coalesce((select max(id) from "config_pos"), 1));

-- 3. Que PostgREST vea las columnas nuevas sin esperar el refresco solo.
notify pgrst, 'reload schema';
