-- ═══════════════════════════════════════════════════════════════════════════
-- Remuneraciones (RRHH) — sueldos, liquidaciones y su histórico
-- Correr en el SQL editor de Supabase «Alma Animal» (ixqharypfqlooogoctdp).
-- Idempotente: se puede re-ejecutar sin romper nada.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Reemplaza el Excel con Solver que se corría a mano cada mes. Cuatro tablas:
--   rrhh_empleados     — el contrato y la previsión de cada trabajador.
--   rrhh_parametros    — los valores legales POR PERÍODO (UF, UTM, topes,
--                        tasas). Es lo que impide que el módulo envejezca: los
--                        topes imponibles se reajustan cada año y el aporte
--                        previsional del empleador (Ley 21.735) sube todos los
--                        años hasta 2033.
--   rrhh_liquidaciones — una por empleado y período, con el desglose y los
--                        parámetros CONGELADOS en JSON, para que reimprimir
--                        enero en diciembre dé exactamente el mismo PDF.
--   rrhh_pagos         — la orden de pago mensual (lo que se transfiere).
--
-- Los CREATE son idénticos a los que emite scripts/generar-schema-sql.ts desde
-- lib/sheets-schema.ts, para que un entorno nuevo y este queden iguales.

-- ── 1) Empleados ────────────────────────────────────────────────────────────
-- No se borran nunca (romperían el histórico): se desactivan con activo=FALSE.
-- `usuario_id` enlaza opcionalmente con `usuarios` para traer las horas extra
-- desde `asistencia`.
create table if not exists "rrhh_empleados" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "nombre_completo" text not null default '',   -- como debe salir en la liquidación
  "rut" text not null default '',
  "fecha_nacimiento" text not null default '',
  "nacionalidad" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "cargo" text not null default '',
  "unidad_negocio" text not null default '',
  "tipo_contrato" text not null default '',     -- 'indefinido' | 'plazo_fijo'
  "fecha_ingreso" text not null default '',
  "fecha_termino" text not null default '',
  "jornada_semanal_horas" text not null default '',
  "sueldo_base" text not null default '',
  -- 'meta_liquido'  → el solver ajusta el bono hasta que el líquido dé
  --                   sueldo_base + valor_por_cremacion × cremaciones del mes
  -- 'monto_directo' → se paga valor_por_cremacion × cremaciones como imponible
  -- 'ninguna'       → sin variable
  "modalidad_variable" text not null default '',
  "valor_por_cremacion" text not null default '',
  "haberes_no_imponibles" text not null default '',  -- JSON [{nombre,monto}]
  "afp" text not null default '',
  "prevision_salud" text not null default '',   -- 'fonasa' | 'isapre' | 'no_tiene'
  "isapre_codigo" text not null default '',
  "plan_salud_uf" text not null default '',
  "apv_monto" text not null default '',
  "apv_institucion" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "activo" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_empleados" enable row level security;

-- ── 2) Parámetros legales por período ───────────────────────────────────────
create table if not exists "rrhh_parametros" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',           -- 'YYYY-MM'
  "valor_uf" text not null default '',
  "valor_utm" text not null default '',
  "imm" text not null default '',               -- ingreso mínimo mensual
  "tope_afp_uf" text not null default '',       -- 90,0 UF en 2026 (87,8 en 2025)
  "tope_afc_uf" text not null default '',       -- 135,2 UF en 2026 (131,9 en 2025)
  "tasas_afp" text not null default '',         -- JSON {codigo: tasa%}
  "tramos_impuesto" text not null default '',   -- JSON [{desde_utm,hasta_utm,tasa,rebaja_utm}]
  "tasa_afc_trabajador" text not null default '',
  "tasa_afc_empleador_indefinido" text not null default '',
  "tasa_afc_empleador_plazo_fijo" text not null default '',
  "tasa_mutual" text not null default '',
  -- Ley 21.735. Hasta jul-2026: SIS 1,38 + cuenta individual 0,1 + FAPP 0,9.
  -- Desde ago-2026 el SIS se absorbe y el total pasa a 3,5%
  -- (0,1 cuenta individual + 0,9 FAPP + 2,5 seguro social).
  "tasa_sis" text not null default '',
  "tasa_cuenta_individual" text not null default '',
  "tasa_fapp" text not null default '',
  "tasa_seguro_social" text not null default '',
  "factor_gratificacion" text not null default '',
  "tope_gratificacion_imm" text not null default '',
  "dias_habiles" text not null default '',      -- override del calendario (vacío = calculado)
  "dias_descanso" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_parametros" enable row level security;
create index if not exists "rrhh_parametros_periodo_idx" on "rrhh_parametros" ("periodo");
create unique index if not exists "rrhh_parametros_periodo_uniq" on "rrhh_parametros" ("periodo");

-- ── 3) Liquidaciones ────────────────────────────────────────────────────────
create table if not exists "rrhh_liquidaciones" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',
  "empleado_id" text not null default '',
  "empleado_nombre" text not null default '',
  "estado" text not null default '',            -- 'borrador' | 'cerrada' | 'pagada'
  "cremaciones" text not null default '',
  "meta_liquido" text not null default '',
  "variable_imponible" text not null default '',
  "total_imponible" text not null default '',
  "total_no_imponible" text not null default '',
  "total_haberes" text not null default '',
  "total_descuentos" text not null default '',
  "impuesto_unico" text not null default '',
  "liquido" text not null default '',
  "reembolso_salud" text not null default '',   -- sin previsión: el 7% se paga aparte
  "total_a_transferir" text not null default '',
  "aportes_empleador" text not null default '',
  "costo_empresa" text not null default '',
  "exacto" text not null default '',            -- el solver alcanzó la meta al peso
  "diferencia_meta" text not null default '',
  "detalle_json" text not null default '',      -- líneas con etiqueta, monto y fórmula
  "parametros_json" text not null default '',   -- snapshot congelado
  "novedades_json" text not null default '',    -- horas extra, anticipos, ausencias, bonos
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "fecha_pago" text not null default '',
  "cerrada_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_liquidaciones" enable row level security;
create index if not exists "rrhh_liquidaciones_periodo_idx" on "rrhh_liquidaciones" ("periodo");
create index if not exists "rrhh_liquidaciones_empleado_id_idx" on "rrhh_liquidaciones" ("empleado_id");
-- Un período no puede tener dos liquidaciones del mismo empleado.
create unique index if not exists "rrhh_liquidaciones_periodo_empleado_uniq"
  on "rrhh_liquidaciones" ("periodo", "empleado_id");

-- ── 4) Orden de pago del mes ────────────────────────────────────────────────
create table if not exists "rrhh_pagos" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',
  "liquidacion_ids" text not null default '',   -- JSON
  "total_liquidos" text not null default '',
  "total_reembolsos" text not null default '',
  "total_transferido" text not null default '',
  "costo_empresa" text not null default '',
  "fecha_pago" text not null default '',
  "comentarios" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_pagos" enable row level security;
create index if not exists "rrhh_pagos_periodo_idx" on "rrhh_pagos" ("periodo");
create unique index if not exists "rrhh_pagos_periodo_uniq" on "rrhh_pagos" ("periodo");

-- ── 5) Enganche con el Estado de Resultados ─────────────────────────────────
-- El costo de remuneraciones NO se carga a mano en eerr_gastos_manuales: el EERR
-- lee directo las liquidaciones pagadas, igual que hace con los pagos de retiros
-- adicionales (lib/eerr-retiros.ts). Basta con marcar la partida 'Personal' con
-- una clave; de ahí en adelante lib/remuneraciones/eerr.ts la alimenta sola. Así
-- una liquidación corregida se refleja al instante y no hay doble conteo.
update "eerr_partidas"
   set "clave" = 'remuneraciones'
 where "tipo" = 'gasto' and "nombre" = 'Personal' and coalesce("clave", '') = '';

-- ⚠️ Si hasta ahora los sueldos se cargaban a mano en Compras / Gastos manuales
-- bajo la partida Personal, hay que BORRAR esas filas o quedarán duplicadas:
--   select * from eerr_gastos_manuales
--    where partida_id = (select id from eerr_partidas where tipo='gasto' and nombre='Personal');

-- ── 6) Realineación de secuencias ───────────────────────────────────────────
select reset_id_seq('rrhh_empleados');
select reset_id_seq('rrhh_parametros');
select reset_id_seq('rrhh_liquidaciones');
select reset_id_seq('rrhh_pagos');

-- Que PostgREST vea las tablas nuevas sin esperar los ~30 s de recarga.
notify pgrst, 'reload schema';
