-- Esquema principal (Sheets → Postgres). GENERADO por scripts/generar-schema-sql.ts
-- Correr en el SQL editor del proyecto Supabase de mailing (SUPABASE_URL).
-- Columnas en text (drop-in); id como identity. Ver docs/migracion-postgres.md.

-- getNextId atómico (reemplaza el max(id)+1 con race de Sheets)
create or replace function next_id(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select nextval(%L)', seq) into v;
  return v;
end $$;

-- Ajusta el sequence de id al max(id) actual (correr tras el import)
create or replace function reset_id_seq(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select coalesce(max(id),0) from %I', p_table) into v;
  perform setval(seq, greatest(v, 1), v > 0);
  return v;
end $$;

create table if not exists "clientes" (
  "id" bigint generated by default as identity primary key,
  "codigo" text not null default '',
  "nombre_mascota" text not null default '',
  "nombre_tutor" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "direccion_retiro" text not null default '',
  "direccion_despacho" text not null default '',
  "misma_direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "fecha_defuncion" text not null default '',
  "especie" text not null default '',
  "letra_especie" text not null default '',
  "peso_declarado" text not null default '',
  "peso_ingreso" text not null default '',
  "tipo_servicio" text not null default '',
  "codigo_servicio" text not null default '',
  "estado" text not null default '',
  "ciclo_id" text not null default '',
  "despacho_id" text not null default '',
  "veterinaria_id" text not null default '',
  "tipo_precios" text not null default '',
  "adicionales" text not null default '',
  "descuento_id" text not null default '',
  "descuento_nombre" text not null default '',
  "descuento_tipo" text not null default '',
  "descuento_valor" text not null default '',
  "descuento_monto" text not null default '',
  "precio_servicio" text not null default '',
  "precio_adicionales" text not null default '',
  "precio_total" text not null default '',
  "notas" text not null default '',
  "tipo_pago" text not null default '',
  "estado_pago" text not null default '',
  "fotos_mascota" text not null default '',
  "videos_servicio" text not null default '',
  "origen" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "clientes" enable row level security;
create index if not exists "clientes_estado_idx" on "clientes" ("estado");
create index if not exists "clientes_codigo_idx" on "clientes" ("codigo");
create index if not exists "clientes_ciclo_id_idx" on "clientes" ("ciclo_id");
create index if not exists "clientes_despacho_id_idx" on "clientes" ("despacho_id");
create index if not exists "clientes_veterinaria_id_idx" on "clientes" ("veterinaria_id");

create table if not exists "ciclos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_ciclo" text not null default '',
  "litros_inicio" text not null default '',
  "litros_fin" text not null default '',
  "mascotas_ids" text not null default '',
  "comentarios" text not null default '',
  "hora_inicio" text not null default '',
  "hora_fin" text not null default '',
  "temperatura_camara" text not null default '',
  "peso_total" text not null default '',
  "lt_kg" text not null default '',
  "lt_mascota" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "ciclos" enable row level security;
create index if not exists "ciclos_fecha_idx" on "ciclos" ("fecha");

create table if not exists "cargas_petroleo" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "precio_neto" text not null default '',
  "iva" text not null default '',
  "especifico" text not null default '',
  "total_bruto" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "cargas_petroleo" enable row level security;

create table if not exists "vehiculo_cargas" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "km_odometro" text not null default '',
  "monto" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vehiculo_cargas" enable row level security;

create table if not exists "despachos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_recorrido" text not null default '',
  "numero_global" text not null default '',
  "mascotas_ids" text not null default '',
  "nota" text not null default '',
  "fecha_creacion" text not null default '',
  "estado_ruta" text not null default '',
  "origen_direccion" text not null default '',
  "origen_lat" text not null default '',
  "origen_lng" text not null default '',
  "destino_direccion" text not null default '',
  "destino_lat" text not null default '',
  "destino_lng" text not null default '',
  "paradas" text not null default '',
  "entregas" text not null default '',
  "hora_inicio_ruta" text not null default '',
  "hora_termino_ruta" text not null default '',
  "fecha_realizada" text not null default ''
);
alter table "despachos" enable row level security;
create index if not exists "despachos_estado_ruta_idx" on "despachos" ("estado_ruta");

create table if not exists "rendiciones" (
  "id" bigint generated by default as identity primary key,
  "usuario" text not null default '',
  "descripcion" text not null default '',
  "fecha" text not null default '',
  "monto" text not null default '',
  "tipo_documento" text not null default '',
  "estado" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rendiciones" enable row level security;

create table if not exists "pagos_rendicion" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_pagado" text not null default '',
  "rendicion_ids" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_rendicion" enable row level security;

create table if not exists "veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "nombre_contacto" text not null default '',
  "cargo_contacto" text not null default '',
  "tipo_precios" text not null default '',
  "precios_especiales" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "veterinarios" enable row level security;

create table if not exists "precios_generales" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_generales" enable row level security;

create table if not exists "precios_convenio" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_convenio" enable row level security;

create table if not exists "precios_especiales" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_especiales" enable row level security;

create table if not exists "productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "categoria" text not null default '',
  "precio" text not null default '',
  "foto_url" text not null default '',
  "stock" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "productos" enable row level security;

create table if not exists "categorias_productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "categorias_productos" enable row level security;

create table if not exists "informes_veterinaria" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "veterinaria_nombre" text not null default '',
  "version" text not null default '',
  "formato" text not null default '',
  "periodo_hasta_mes" text not null default '',
  "cantidad_meses" text not null default '',
  "cantidad_fichas" text not null default '',
  "monto_total_clp" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "archivo_key" text not null default '',
  "archivo_url" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "informes_veterinaria" enable row level security;

create table if not exists "especies" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "letra" text not null default '',
  "activo" text not null default ''
);
alter table "especies" enable row level security;

create table if not exists "tipos_servicio" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "codigo" text not null default '',
  "plazo_entrega_dias" text not null default '',
  "activo" text not null default ''
);
alter table "tipos_servicio" enable row level security;

create table if not exists "otros_servicios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "precio" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "otros_servicios" enable row level security;

create table if not exists "descuentos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "tipo" text not null default '',
  "valor" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "descuentos" enable row level security;

create table if not exists "usuarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "password" text not null default '',
  "rol" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "usuarios" enable row level security;

create table if not exists "asistencia" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "dia_semana" text not null default '',
  "es_findesemana" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "minutos_trabajados" text not null default '',
  "minutos_normales" text not null default '',
  "minutos_extra" text not null default '',
  "estado_aprobacion" text not null default '',
  "aprobado_por" text not null default '',
  "comentario" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "asistencia" enable row level security;
create index if not exists "asistencia_fecha_idx" on "asistencia" ("fecha");

create table if not exists "jornada_config" (
  "id" bigint generated by default as identity primary key,
  "vigente_desde" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "precio_hora_extra" text not null default '',
  "tolerancia_minutos" text not null default '',
  "precio_retiro_adicional" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "jornada_config" enable row level security;

create table if not exists "retiros_adicionales" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "hora" text not null default '',
  "cliente_nombre" text not null default '',
  "comentario" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "retiros_adicionales" enable row level security;

create table if not exists "pagos_retiros" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "retiros_ids" text not null default '',
  "cantidad" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_retiros" enable row level security;

create table if not exists "certificados" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "codigo_mascota" text not null default '',
  "nombre_mascota" text not null default '',
  "version" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "sin_foto" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "enviado_ultima_fecha" text not null default '',
  "enviado_ultima_hora" text not null default '',
  "enviado_cantidad" text not null default '',
  "enviado_a" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "certificados" enable row level security;
create index if not exists "certificados_cliente_id_idx" on "certificados" ("cliente_id");

create table if not exists "geocoding_cache" (
  "id" bigint generated by default as identity primary key,
  "direccion_normalizada" text not null default '',
  "direccion_original" text not null default '',
  "lat" text not null default '',
  "lng" text not null default '',
  "formatted_address" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "geocoding_cache" enable row level security;

create table if not exists "empresa_config" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "web" text not null default '',
  "instagram" text not null default '',
  "facebook" text not null default '',
  "google_review_url" text not null default '',
  "email_seguimiento" text not null default '',
  "email_seguimiento_activo" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "empresa_config" enable row level security;

create table if not exists "mailing_veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "veterinaria" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "categoria" text not null default '',
  "tamano_veterinaria" text not null default '',
  "suscrito" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_veterinarios" enable row level security;
create index if not exists "mailing_veterinarios_email_idx" on "mailing_veterinarios" ("email");

create table if not exists "mailing_campanas" (
  "id" bigint generated by default as identity primary key,
  "asunto" text not null default '',
  "html_key" text not null default '',
  "html_url" text not null default '',
  "preview_text" text not null default '',
  "reply_to" text not null default '',
  "fecha_envio" text not null default '',
  "hora_envio" text not null default '',
  "total_destinatarios" text not null default '',
  "enviados" text not null default '',
  "entregados" text not null default '',
  "aperturas" text not null default '',
  "clicks" text not null default '',
  "rebotes" text not null default '',
  "spam" text not null default '',
  "fallidos" text not null default '',
  "estado" text not null default '',
  "filtros_json" text not null default '',
  "attachments_json" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_campanas" enable row level security;

create table if not exists "vet_convenio_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "apellido" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "rut" text not null default '',
  "comunas" text not null default '',
  "horarios" text not null default '',
  "activo" text not null default '',
  "origen" text not null default '',
  "notas" text not null default '',
  "total_servicios" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "datos_pago_completos" text not null default '',
  "fecha_datos_pago" text not null default '',
  "fecha_inscripcion" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vet_convenio_eutanasia" enable row level security;

create table if not exists "precios_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio" text not null default ''
);
alter table "precios_eutanasia" enable row level security;

create table if not exists "config_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "fijo" text not null default ''
);
alter table "config_eutanasia" enable row level security;

create table if not exists "cotizaciones_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "mascota_nombre" text not null default '',
  "especie" text not null default '',
  "peso" text not null default '',
  "cliente_nombre" text not null default '',
  "cliente_telefono" text not null default '',
  "cliente_email" text not null default '',
  "cliente_wa_id" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_servicio" text not null default '',
  "hora_servicio" text not null default '',
  "notas" text not null default '',
  "estado" text not null default '',
  "vet_id_asignado" text not null default '',
  "vet_nombre_asignado" text not null default '',
  "vet_email_asignado" text not null default '',
  "precio_snapshot" text not null default '',
  "estado_pago" text not null default '',
  "fecha_pago" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_envio_cotizacion" text not null default '',
  "fecha_aceptacion" text not null default '',
  "fecha_confirmacion" text not null default '',
  "fecha_realizacion" text not null default '',
  "fecha_cancelacion" text not null default '',
  "creado_por" text not null default ''
);
alter table "cotizaciones_eutanasia" enable row level security;
create index if not exists "cotizaciones_eutanasia_estado_idx" on "cotizaciones_eutanasia" ("estado");
create index if not exists "cotizaciones_eutanasia_vet_id_asignado_idx" on "cotizaciones_eutanasia" ("vet_id_asignado");

create table if not exists "cotizaciones_eutanasia_envios" (
  "id" bigint generated by default as identity primary key,
  "cotizacion_id" text not null default '',
  "vet_id" text not null default '',
  "vet_email" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_respuesta" text not null default '',
  "estado_envio" text not null default '',
  "resend_message_id" text not null default ''
);
alter table "cotizaciones_eutanasia_envios" enable row level security;
create index if not exists "cotizaciones_eutanasia_envios_cotizacion_id_idx" on "cotizaciones_eutanasia_envios" ("cotizacion_id");
create index if not exists "cotizaciones_eutanasia_envios_vet_id_idx" on "cotizaciones_eutanasia_envios" ("vet_id");

create table if not exists "solicitudes_retiro" (
  "id" bigint generated by default as identity primary key,
  "cliente_wa_id" text not null default '',
  "cliente_nombre" text not null default '',
  "nombre_mascota" text not null default '',
  "peso" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "hora_retiro" text not null default '',
  "tipo_servicio" text not null default '',
  "estado" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_resolucion" text not null default ''
);
alter table "solicitudes_retiro" enable row level security;
create index if not exists "solicitudes_retiro_estado_idx" on "solicitudes_retiro" ("estado");
create index if not exists "solicitudes_retiro_cliente_wa_id_idx" on "solicitudes_retiro" ("cliente_wa_id");

-- Banco de imágenes para campañas de mailing (generadas con Nano Banana Pro o
-- subidas a mano). Viven en R2 (url/key) y se reciclan entre correos: el
-- generador IA revisa este banco y reutiliza una imagen cuando calza.
create table if not exists "mailing_imagenes" (
  "id" bigint generated by default as identity primary key,
  "url" text not null default '',
  "key" text not null default '',
  "descripcion" text not null default '',
  "prompt" text not null default '',
  "tags" text not null default '',
  "alt" text not null default '',
  "grupo" text not null default '',
  "aspect" text not null default '',
  "ancho" text not null default '',
  "alto" text not null default '',
  "origen" text not null default '',
  "modelo" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_imagenes" enable row level security;

-- Correos transaccionales al tutor (registro / inicio cremación / inicio
-- despacho / entrega / certificado). Se registran al enviar y el webhook de
-- Resend reconcilia entregado/abierto/rebotado por message_id.
create table if not exists "correos_cliente" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "tipo" text not null default '',
  "email" text not null default '',
  "message_id" text not null default '',
  "estado" text not null default '',
  "motivo" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "correos_cliente" enable row level security;
create index if not exists "correos_cliente_cliente_id_idx" on "correos_cliente" ("cliente_id");
create index if not exists "correos_cliente_message_id_idx" on "correos_cliente" ("message_id");
create index if not exists "correos_cliente_email_idx" on "correos_cliente" ("email");
