-- Esquema principal (Sheets → Postgres). GENERADO por scripts/generar-schema-sql.ts
-- Correr en el SQL editor del proyecto Supabase de mailing (SUPABASE_URL).
-- Columnas en text (drop-in); id como identity. Ver docs/migracion-postgres.md.

-- getNextId atómico (reemplaza el max(id)+1 con race de Sheets)
create or replace function next_id(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select nextval(%L)', seq) into v;
  return v;
end $$;

-- Ajusta el sequence de id al max(id) actual (correr tras el import)
create or replace function reset_id_seq(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select coalesce(max(id),0) from %I', p_table) into v;
  perform setval(seq, greatest(v, 1), v > 0);
  return v;
end $$;

create table if not exists "clientes" (
  "id" bigint generated by default as identity primary key,
  "codigo" text not null default '',
  "nombre_mascota" text not null default '',
  "nombre_tutor" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "direccion_retiro" text not null default '',
  "direccion_despacho" text not null default '',
  "misma_direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "fecha_defuncion" text not null default '',
  "fecha_nacimiento" text not null default '',
  "especie" text not null default '',
  "letra_especie" text not null default '',
  "peso_declarado" text not null default '',
  "peso_ingreso" text not null default '',
  "tipo_servicio" text not null default '',
  "codigo_servicio" text not null default '',
  "estado" text not null default '',
  "ciclo_id" text not null default '',
  "despacho_id" text not null default '',
  "veterinaria_id" text not null default '',
  "tipo_precios" text not null default '',
  "adicionales" text not null default '',
  "descuento_id" text not null default '',
  "descuento_nombre" text not null default '',
  "descuento_tipo" text not null default '',
  "descuento_valor" text not null default '',
  "descuento_monto" text not null default '',
  "precio_servicio" text not null default '',
  "precio_adicionales" text not null default '',
  "precio_total" text not null default '',
  "notas" text not null default '',
  "tipo_pago" text not null default '',
  "estado_pago" text not null default '',
  "omitir_evaluacion" text not null default 'FALSE',
  "fotos_mascota" text not null default '',
  "fotos_cuadro" text not null default '',
  "videos_servicio" text not null default '',
  "origen" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "clientes" enable row level security;
create index if not exists "clientes_estado_idx" on "clientes" ("estado");
create index if not exists "clientes_codigo_idx" on "clientes" ("codigo");
create index if not exists "clientes_ciclo_id_idx" on "clientes" ("ciclo_id");
create index if not exists "clientes_despacho_id_idx" on "clientes" ("despacho_id");
create index if not exists "clientes_veterinaria_id_idx" on "clientes" ("veterinaria_id");
-- Si 'TRUE', el correo de entrega va SIN el pedido de evaluación (clientes conflictivos).
alter table "clientes" add column if not exists "omitir_evaluacion" text not null default 'FALSE';
-- Fotos que el tutor sube para el cuadro acuarela conmemorativo (Premium/CP).
alter table "clientes" add column if not exists "fotos_cuadro" text not null default '';
-- Correo de cobro por diferencia de peso (fecha de envío + monto cobrado); vacío = no enviado.
alter table "clientes" add column if not exists "correo_diferencia_fecha" text not null default '';
alter table "clientes" add column if not exists "correo_diferencia_monto" text not null default '';
-- id del documento_tributarios (factura al veterinario) que ya cubrió esta ficha;
-- vacío = no facturada aún al vet (la excluye de la próxima propuesta mensual).
alter table "clientes" add column if not exists "factura_vet_id" text not null default '';
-- boleta_id: id del documento (boleta 39) emitido AL TUTOR cuando la ficha pasó a
-- pagada. vacío = no se emitió aún (guard de idempotencia del auto-emisor de boleta).
alter table "clientes" add column if not exists "boleta_id" text default '';
-- hora_retiro (HH:MM): hora coordinada del retiro. Junto con fecha_retiro determina
-- si aplica el recargo automático "fuera de horario" (>=18:00 L-V, o sáb/dom).
alter table "clientes" add column if not exists "hora_retiro" text not null default '';
-- greda_descontada: ánfora de greda descontada del stock por esta ficha (solo
-- Cremación Individual, por tramo de peso 0-10 S / 10-30 M / 30+ L, ver
-- lib/greda-stock.ts). '' = ficha legada sin tracking (no tocar) · '-' = tracked
-- sin greda (otro servicio / sin peso) · '<id>' = producto de Bodega descontado.
alter table "clientes" add column if not exists "greda_descontada" text not null default '';
-- fecha_nacimiento: fecha de nacimiento de la mascota (informativa, junto a fecha_defuncion).
alter table "clientes" add column if not exists "fecha_nacimiento" text not null default '';

create table if not exists "ciclos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_ciclo" text not null default '',
  "litros_inicio" text not null default '',
  "litros_fin" text not null default '',
  "mascotas_ids" text not null default '',
  "comentarios" text not null default '',
  "hora_inicio" text not null default '',
  "hora_fin" text not null default '',
  "temperatura_camara" text not null default '',
  "peso_total" text not null default '',
  "lt_kg" text not null default '',
  "lt_mascota" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "ciclos" enable row level security;
create index if not exists "ciclos_fecha_idx" on "ciclos" ("fecha");

create table if not exists "cargas_petroleo" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "precio_neto" text not null default '',
  "iva" text not null default '',
  "especifico" text not null default '',
  "total_bruto" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "cargas_petroleo" enable row level security;

create table if not exists "vehiculo_cargas" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "km_odometro" text not null default '',
  "monto" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vehiculo_cargas" enable row level security;

create table if not exists "despachos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_recorrido" text not null default '',
  "numero_global" text not null default '',
  "mascotas_ids" text not null default '',
  "nota" text not null default '',
  "fecha_creacion" text not null default '',
  "estado_ruta" text not null default '',
  "origen_direccion" text not null default '',
  "origen_lat" text not null default '',
  "origen_lng" text not null default '',
  "destino_direccion" text not null default '',
  "destino_lat" text not null default '',
  "destino_lng" text not null default '',
  "paradas" text not null default '',
  "entregas" text not null default '',
  "hora_inicio_ruta" text not null default '',
  "hora_termino_ruta" text not null default '',
  "fecha_realizada" text not null default ''
);
alter table "despachos" enable row level security;
create index if not exists "despachos_estado_ruta_idx" on "despachos" ("estado_ruta");

create table if not exists "rendiciones" (
  "id" bigint generated by default as identity primary key,
  "usuario" text not null default '',
  "descripcion" text not null default '',
  "fecha" text not null default '',
  "monto" text not null default '',
  "tipo_documento" text not null default '',
  "clasificacion" text not null default 'rendicion',
  "estado" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rendiciones" enable row level security;

create table if not exists "pagos_rendicion" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_pagado" text not null default '',
  "rendicion_ids" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_rendicion" enable row level security;

create table if not exists "veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "nombre_contacto" text not null default '',
  "cargo_contacto" text not null default '',
  "tipo_precios" text not null default '',
  "precios_especiales" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "veterinarios" enable row level security;

create table if not exists "precios_generales" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_generales" enable row level security;

create table if not exists "precios_convenio" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_convenio" enable row level security;

create table if not exists "precios_especiales" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_especiales" enable row level security;

create table if not exists "productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "categoria" text not null default '',
  "precio" text not null default '',
  "foto_url" text not null default '',
  "stock" text not null default '',
  "activo" text not null default '',
  "mostrar_web" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "productos" enable row level security;
-- Módulo Web: mostrar/ocultar el producto en la web (vacío = visible; 'FALSE' = oculto).
alter table "productos" add column if not exists "mostrar_web" text not null default '';

create table if not exists "categorias_productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "categorias_productos" enable row level security;

create table if not exists "informes_veterinaria" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "veterinaria_nombre" text not null default '',
  "version" text not null default '',
  "formato" text not null default '',
  "periodo_hasta_mes" text not null default '',
  "cantidad_meses" text not null default '',
  "cantidad_fichas" text not null default '',
  "monto_total_clp" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "archivo_key" text not null default '',
  "archivo_url" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "informes_veterinaria" enable row level security;

create table if not exists "especies" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "letra" text not null default '',
  "activo" text not null default ''
);
alter table "especies" enable row level security;

create table if not exists "tipos_servicio" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "codigo" text not null default '',
  "plazo_entrega_dias" text not null default '',
  "activo" text not null default ''
);
alter table "tipos_servicio" enable row level security;

create table if not exists "otros_servicios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "precio" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "otros_servicios" enable row level security;
-- auto_regla: '' | 'fuera_horario' | 'distancia' — el servicio se pre-carga solo en la
-- ficha (deseleccionable) cuando aplica la regla (ver lib/adicionales-auto.ts).
alter table "otros_servicios" add column if not exists "auto_regla" text not null default '';
-- comunas (JSON array de nombres): solo para auto_regla='distancia' — comunas con recargo.
alter table "otros_servicios" add column if not exists "comunas" text not null default '';

-- Cobros que perseguimos por ficha: producto ADICIONAL agregado o DIFERENCIA de
-- peso. estado: pendiente → cliente_confirmo → pagado.
create table if not exists "cobros" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "tipo" text not null default '',
  "detalle" text not null default '',
  "monto" text not null default '0',
  "estado" text not null default 'pendiente',
  "message_id" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_cliente_confirmo" text not null default '',
  "fecha_pagado" text not null default ''
);
alter table "cobros" enable row level security;
create index if not exists "cobros_cliente_idx" on "cobros" ("cliente_id");

create table if not exists "descuentos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "tipo" text not null default '',
  "valor" text not null default '',
  "activo" text not null default '',
  "foto_url" text not null default '',
  "mostrar_web" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "descuentos" enable row level security;
-- Módulo Web: logo/imagen del convenio + mostrar en web (vacío = oculto; 'TRUE' = visible).
alter table "descuentos" add column if not exists "foto_url" text not null default '';
alter table "descuentos" add column if not exists "mostrar_web" text not null default '';

-- ── Módulo Web: contenido editable del sitio público (panel "Web") ───────────
create table if not exists "web_servicios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "slug" text not null default '',
  "resumen" text not null default '',
  "descripcion" text not null default '',
  "foto_url" text not null default '',
  "precio_desde" text not null default '',
  "orden" text not null default '',
  "publicado" text not null default '',
  "seo_titulo" text not null default '',
  "seo_desc" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_servicios" enable row level security;

create table if not exists "web_posts" (
  "id" bigint generated by default as identity primary key,
  "titulo" text not null default '',
  "slug" text not null default '',
  "categoria" text not null default '',
  "extracto" text not null default '',
  "contenido" text not null default '',
  "foto_url" text not null default '',
  "autor" text not null default '',
  "fecha" text not null default '',
  "publicado" text not null default '',
  "seo_titulo" text not null default '',
  "seo_desc" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_posts" enable row level security;

create table if not exists "web_paginas" (
  "id" bigint generated by default as identity primary key,
  "pagina" text not null default '',
  "clave" text not null default '',
  "titulo" text not null default '',
  "contenido" text not null default '',
  "foto_url" text not null default '',
  "orden" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_paginas" enable row level security;

create table if not exists "usuarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "password" text not null default '',
  "rol" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default '',
  "telefono" text not null default '',
  "avisos_whatsapp" text not null default 'FALSE'
);
alter table "usuarios" enable row level security;
-- Celular del usuario + opt-in a los avisos del sistema por WhatsApp (2026-07-11):
-- con teléfono y avisos_whatsapp=TRUE el usuario entra a la lista de destinatarios
-- de los avisos/botones del bot (además de ADMIN_WHATSAPP del env).
alter table "usuarios" add column if not exists "telefono" text not null default '';
alter table "usuarios" add column if not exists "avisos_whatsapp" text not null default 'FALSE';

create table if not exists "asistencia" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "dia_semana" text not null default '',
  "es_findesemana" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "minutos_trabajados" text not null default '',
  "minutos_normales" text not null default '',
  "minutos_extra" text not null default '',
  "estado_aprobacion" text not null default '',
  "aprobado_por" text not null default '',
  "comentario" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "asistencia" enable row level security;
create index if not exists "asistencia_fecha_idx" on "asistencia" ("fecha");

create table if not exists "jornada_config" (
  "id" bigint generated by default as identity primary key,
  "vigente_desde" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "precio_hora_extra" text not null default '',
  "tolerancia_minutos" text not null default '',
  "precio_retiro_adicional" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "jornada_config" enable row level security;

create table if not exists "retiros_adicionales" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "hora" text not null default '',
  "cliente_nombre" text not null default '',
  "comentario" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "retiros_adicionales" enable row level security;

create table if not exists "pagos_retiros" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "retiros_ids" text not null default '',
  "cantidad" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_retiros" enable row level security;

create table if not exists "documentos_tributarios" (
  "id" bigint generated by default as identity primary key,
  "tipo_dte" text not null default '',
  "folio" text not null default '',
  "estado" text not null default 'emitido',
  "ambiente" text not null default '',
  "fecha_emision" text not null default '',
  "receptor_tipo" text not null default '',
  "receptor_id" text not null default '',
  "receptor_rut" text not null default '',
  "receptor_razon_social" text not null default '',
  "receptor_giro" text not null default '',
  "receptor_direccion" text not null default '',
  "receptor_comuna" text not null default '',
  "receptor_correo" text not null default '',
  "monto_neto" text not null default '',
  "monto_iva" text not null default '',
  "monto_total" text not null default '',
  "detalle_json" text not null default '[]',
  "resumen" text not null default '',
  "mes_facturado" text not null default '',
  "fichas_json" text not null default '[]',
  "openfactura_url" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "documento_anulado_id" text not null default '',
  "nc_id" text not null default '',
  "motivo_anulacion" text not null default '',
  "warnings_json" text not null default '[]',
  "creado_por_id" text not null default '',
  "creado_por_nombre" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "documentos_tributarios" enable row level security;
create index if not exists "documentos_tributarios_tipo_dte_idx" on "documentos_tributarios" ("tipo_dte");
create index if not exists "documentos_tributarios_estado_idx" on "documentos_tributarios" ("estado");
create index if not exists "documentos_tributarios_receptor_id_idx" on "documentos_tributarios" ("receptor_id");
create index if not exists "documentos_tributarios_mes_facturado_idx" on "documentos_tributarios" ("mes_facturado");

create table if not exists "certificados" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "codigo_mascota" text not null default '',
  "nombre_mascota" text not null default '',
  "version" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "sin_foto" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "enviado_ultima_fecha" text not null default '',
  "enviado_ultima_hora" text not null default '',
  "enviado_cantidad" text not null default '',
  "enviado_a" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "certificados" enable row level security;
create index if not exists "certificados_cliente_id_idx" on "certificados" ("cliente_id");

create table if not exists "geocoding_cache" (
  "id" bigint generated by default as identity primary key,
  "direccion_normalizada" text not null default '',
  "direccion_original" text not null default '',
  "lat" text not null default '',
  "lng" text not null default '',
  "formatted_address" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "geocoding_cache" enable row level security;

create table if not exists "empresa_config" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "web" text not null default '',
  "instagram" text not null default '',
  "facebook" text not null default '',
  "google_review_url" text not null default '',
  "email_seguimiento" text not null default '',
  "email_seguimiento_activo" text not null default '',
  "seguimiento_tipos" text not null default '',
  -- Datos de transferencia bancaria (correos de cobro: diferencia y adicionales).
  "titular_cuenta" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "empresa_config" enable row level security;
-- Idempotente para entornos ya creados:
alter table "empresa_config" add column if not exists "seguimiento_tipos" text not null default '';
alter table "empresa_config" add column if not exists "titular_cuenta" text not null default '';
alter table "empresa_config" add column if not exists "banco" text not null default '';
alter table "empresa_config" add column if not exists "tipo_cuenta" text not null default '';
alter table "empresa_config" add column if not exists "numero_cuenta" text not null default '';

create table if not exists "mailing_veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "veterinaria" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "categoria" text not null default '',
  "tamano_veterinaria" text not null default '',
  "suscrito" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_veterinarios" enable row level security;
create index if not exists "mailing_veterinarios_email_idx" on "mailing_veterinarios" ("email");

create table if not exists "mailing_campanas" (
  "id" bigint generated by default as identity primary key,
  "asunto" text not null default '',
  "html_key" text not null default '',
  "html_url" text not null default '',
  "preview_text" text not null default '',
  "reply_to" text not null default '',
  "fecha_envio" text not null default '',
  "hora_envio" text not null default '',
  "total_destinatarios" text not null default '',
  "enviados" text not null default '',
  "entregados" text not null default '',
  "aperturas" text not null default '',
  "clicks" text not null default '',
  "rebotes" text not null default '',
  "spam" text not null default '',
  "fallidos" text not null default '',
  "estado" text not null default '',
  "filtros_json" text not null default '',
  "attachments_json" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_campanas" enable row level security;

create table if not exists "vet_convenio_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "apellido" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "rut" text not null default '',
  "comunas" text not null default '',
  "horarios" text not null default '',
  "activo" text not null default '',
  "origen" text not null default '',
  "notas" text not null default '',
  "total_servicios" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "datos_pago_completos" text not null default '',
  "fecha_datos_pago" text not null default '',
  "fecha_inscripcion" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vet_convenio_eutanasia" enable row level security;

create table if not exists "precios_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio" text not null default ''
);
alter table "precios_eutanasia" enable row level security;

create table if not exists "config_eutanasia" (
  "id" bigint generated by default as identity primary key,
  -- fijo: cargo fijo al cliente que se SUMA al pago al vet para el precio al cliente
  -- cuando la eutanasia SÍ se realiza (precio al cliente = tramo + fijo).
  "fijo" text not null default '',
  -- Consulta cobrada cuando la eutanasia NO se realiza (evaluación a domicilio):
  -- total al cliente = consulta_vet + consulta_alma. El vet cobra consulta_vet.
  "consulta_vet" text not null default '30000',
  "consulta_alma" text not null default '10000',
  -- Recargo al cliente si el servicio de eutanasia es fuera de horario (finde,
  -- feriado o >=18:00 L-V). Se cobra una sola vez junto con la eutanasia, aparte
  -- de la boleta; si además hay cremación, el retiro no vuelve a sumar su recargo.
  "recargo_fuera_horario" text not null default '10000'
);
alter table "config_eutanasia" enable row level security;
alter table "config_eutanasia" add column if not exists "consulta_vet" text not null default '30000';
alter table "config_eutanasia" add column if not exists "consulta_alma" text not null default '10000';
alter table "config_eutanasia" add column if not exists "recargo_fuera_horario" text not null default '10000';

create table if not exists "cotizaciones_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "mascota_nombre" text not null default '',
  "especie" text not null default '',
  "peso" text not null default '',
  "cliente_nombre" text not null default '',
  "cliente_telefono" text not null default '',
  "cliente_email" text not null default '',
  "cliente_wa_id" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_servicio" text not null default '',
  "hora_servicio" text not null default '',
  "notas" text not null default '',
  "estado" text not null default '',
  "vet_id_asignado" text not null default '',
  "vet_nombre_asignado" text not null default '',
  "vet_email_asignado" text not null default '',
  "precio_snapshot" text not null default '',
  "estado_pago" text not null default '',
  "fecha_pago" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_envio_cotizacion" text not null default '',
  "fecha_aceptacion" text not null default '',
  "fecha_confirmacion" text not null default '',
  "fecha_realizacion" text not null default '',
  "fecha_cancelacion" text not null default '',
  "creado_por" text not null default '',
  "tipo_servicio_cremacion" text not null default '',
  "cliente_confirmo" text not null default '',
  "fecha_cliente_confirmacion" text not null default '',
  "incluye_cremacion" text not null default ''
);
alter table "cotizaciones_eutanasia" enable row level security;
-- Columnas del flujo de eutanasia del agente de WhatsApp (idempotente; ya están
-- en la migración supabase/migracion-eutanasia-agente.sql para entornos previos).
alter table "cotizaciones_eutanasia"
  add column if not exists "tipo_servicio_cremacion" text not null default '',
  add column if not exists "cliente_confirmo" text not null default '',
  add column if not exists "fecha_cliente_confirmacion" text not null default '',
  -- cliente_id: ficha borrador de CREMACIÓN creada al agendar la eutanasia. Liga
  -- la cotización a su ficha; el dashboard oculta el cuadro cuando se registra, y
  -- en 'no_realizada' se elimina ese borrador (la mascota sigue viva).
  add column if not exists "cliente_id" text not null default '',
  -- consulta_vet_snapshot: monto a pagar al vet si la eutanasia NO se realiza
  -- (congelado al agendar desde config_eutanasia.consulta_vet).
  add column if not exists "consulta_vet_snapshot" text not null default '',
  -- hora_retiro_crematorio: hora que el vet informa (coordinada con el cliente)
  -- para que el crematorio pase a retirar tras la eutanasia. En blanco hasta que la informe.
  add column if not exists "hora_retiro_crematorio" text not null default '',
  -- incluye_cremacion: 'TRUE'/'FALSE'. Sin cremación → recordatorio gris en el
  -- calendario, sin notificación en el dashboard ni bloqueo de agenda (el chofer
  -- no retira). Vacío = derivar de tipo_servicio_cremacion (solo NINGUNA es sin
  -- cremación). Ver lib/eutanasia-cremacion.
  add column if not exists "incluye_cremacion" text not null default '';
create index if not exists "cotizaciones_eutanasia_estado_idx" on "cotizaciones_eutanasia" ("estado");
create index if not exists "cotizaciones_eutanasia_vet_id_asignado_idx" on "cotizaciones_eutanasia" ("vet_id_asignado");

create table if not exists "cotizaciones_eutanasia_envios" (
  "id" bigint generated by default as identity primary key,
  "cotizacion_id" text not null default '',
  "vet_id" text not null default '',
  "vet_email" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_respuesta" text not null default '',
  "estado_envio" text not null default '',
  "resend_message_id" text not null default ''
);
alter table "cotizaciones_eutanasia_envios" enable row level security;
create index if not exists "cotizaciones_eutanasia_envios_cotizacion_id_idx" on "cotizaciones_eutanasia_envios" ("cotizacion_id");
create index if not exists "cotizaciones_eutanasia_envios_vet_id_idx" on "cotizaciones_eutanasia_envios" ("vet_id");

create table if not exists "solicitudes_retiro" (
  "id" bigint generated by default as identity primary key,
  "cliente_wa_id" text not null default '',
  "cliente_nombre" text not null default '',
  "nombre_mascota" text not null default '',
  "peso" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "hora_retiro" text not null default '',
  "tipo_servicio" text not null default '',
  "estado" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_resolucion" text not null default '',
  -- origen: 'bot_tutor' (default) | 'bot_vet'. Para 'bot_vet' se guarda el vet de
  -- convenio que originó el retiro (liga la ficha y dispara los correos al vet).
  "origen" text not null default '',
  "veterinaria_id" text not null default '',
  "vet_nombre" text not null default '',
  "vet_email" text not null default '',
  -- cliente_id: id de la ficha borrador (clientes) creada al CONFIRMAR el retiro.
  -- Liga la solicitud confirmada a su ficha "Por ingresar"; el dashboard oculta
  -- el cuadro verde cuando esa ficha deja de ser borrador (ya fue registrada).
  "cliente_id" text not null default ''
);
alter table "solicitudes_retiro" enable row level security;
-- Idempotente para tablas creadas antes de estas columnas.
alter table "solicitudes_retiro" add column if not exists "origen" text not null default '';
alter table "solicitudes_retiro" add column if not exists "veterinaria_id" text not null default '';
alter table "solicitudes_retiro" add column if not exists "vet_nombre" text not null default '';
alter table "solicitudes_retiro" add column if not exists "vet_email" text not null default '';
alter table "solicitudes_retiro" add column if not exists "cliente_id" text not null default '';
create index if not exists "solicitudes_retiro_estado_idx" on "solicitudes_retiro" ("estado");
create index if not exists "solicitudes_retiro_cliente_wa_id_idx" on "solicitudes_retiro" ("cliente_wa_id");

-- Banco de imágenes para campañas de mailing (generadas con Nano Banana Pro o
-- subidas a mano). Viven en R2 (url/key) y se reciclan entre correos: el
-- generador IA revisa este banco y reutiliza una imagen cuando calza.
create table if not exists "mailing_imagenes" (
  "id" bigint generated by default as identity primary key,
  "url" text not null default '',
  "key" text not null default '',
  -- codigo: id legible y estable para referirse a la imagen (chat del agente + banco).
  -- i-N = foto suelta/subida; C-X.Y = pieza de campaña (portada/placa/carrusel).
  "codigo" text not null default '',
  "descripcion" text not null default '',
  "prompt" text not null default '',
  "tags" text not null default '',
  "alt" text not null default '',
  "grupo" text not null default '',
  -- subgrupo: etiqueta libre opcional (ej. por campaña) para ordenar sin crear grupos nuevos.
  "subgrupo" text not null default '',
  -- whatsapp: 'TRUE' si el agente de WhatsApp puede enviar esta imagen al cliente
  -- cuando la pida (ej. fotos de ánforas/urnas). Lo marca el equipo a mano.
  "whatsapp" text not null default 'FALSE',
  -- favorita: 'TRUE' si el equipo la destacó con la estrella en el banco.
  "favorita" text not null default 'FALSE',
  "aspect" text not null default '',
  "ancho" text not null default '',
  "alto" text not null default '',
  "origen" text not null default '',
  "modelo" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_imagenes" enable row level security;
-- Idempotente para tablas ya creadas antes de estas columnas.
alter table "mailing_imagenes" add column if not exists "whatsapp" text not null default 'FALSE';
alter table "mailing_imagenes" add column if not exists "subgrupo" text not null default '';
alter table "mailing_imagenes" add column if not exists "codigo" text not null default '';
alter table "mailing_imagenes" add column if not exists "favorita" text not null default 'FALSE';

-- Banco de VIDEOS de campañas (MP4 generados con Veo). Separado del de imágenes.
create table if not exists "mailing_videos" (
  "id" bigint generated by default as identity primary key,
  "url" text not null default '',
  "key" text not null default '',
  -- codigo: ai-N = animado desde una imagen; v-N = video generado sin imagen base.
  "codigo" text not null default '',
  "descripcion" text not null default '',
  "prompt" text not null default '',
  "imagen_origen" text not null default '',
  "aspect" text not null default '',
  "duracion" text not null default '',
  "modelo" text not null default '',
  "favorita" text not null default 'FALSE',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_videos" enable row level security;
alter table "mailing_videos" add column if not exists "codigo" text not null default '';
alter table "mailing_videos" add column if not exists "favorita" text not null default 'FALSE';

-- Correos transaccionales al tutor (registro / inicio cremación / inicio
-- despacho / entrega / certificado). Se registran al enviar y el webhook de
-- Resend reconcilia entregado/abierto/rebotado por message_id.
create table if not exists "correos_cliente" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "tipo" text not null default '',
  "email" text not null default '',
  "message_id" text not null default '',
  "estado" text not null default '',
  "motivo" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "correos_cliente" enable row level security;
create index if not exists "correos_cliente_cliente_id_idx" on "correos_cliente" ("cliente_id");
create index if not exists "correos_cliente_message_id_idx" on "correos_cliente" ("message_id");
create index if not exists "correos_cliente_email_idx" on "correos_cliente" ("email");

-- Registro/respaldo de TODOS los correos transaccionales (cliente + vet +
-- eutanasia; NO las campañas de mailing). Guarda el cuerpo HTML (sin adjuntos)
-- para poder reabrir el correo. Lo escribe sendEmail/sendBatch cuando recibe el
-- campo `seguimiento`. Visor en Configuración → Correos.
create table if not exists "correos_log" (
  "id" bigint generated by default as identity primary key,
  "fecha_envio" text not null default '',
  "tipo" text not null default '',
  "audiencia" text not null default '',
  "destinatario" text not null default '',
  "asunto" text not null default '',
  "cliente_id" text not null default '',
  "codigo" text not null default '',
  "nombre" text not null default '',
  "message_id" text not null default '',
  "estado" text not null default '',
  "motivo" text not null default '',
  "html" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "correos_log" enable row level security;
create index if not exists "correos_log_fecha_idx" on "correos_log" ("fecha_envio" desc);

-- Rate limiting de login (NextAuth Credentials, lib/auth.ts vía lib/login-rate-limit.ts):
-- una fila por intento FALLIDO (email+IP). 5 fallidos en 15 min → bloqueado. Fail-open
-- si Supabase falla (un rate limit caído no debe tumbar el acceso).
create table if not exists "login_intentos" (
  "id" bigint generated by default as identity primary key,
  "email" text not null default '',
  "ip" text not null default '',
  "creado_en" text not null default ''
);
alter table "login_intentos" enable row level security;
create index if not exists "login_intentos_email_ip_idx" on "login_intentos" ("email", "ip", "creado_en");
create index if not exists "correos_log_message_id_idx" on "correos_log" ("message_id");

-- Relay de "¿cuánto falta para el retiro?": el agente avisa al admin y guarda el
-- message_id de ese aviso; cuando el admin responde CITANDO ese mensaje, el
-- webhook reenvía su respuesta al cliente.
create table if not exists "relay_retiro" (
  "id" bigint generated by default as identity primary key,
  "admin_msg_id" text not null default '',
  "cliente_wa_id" text not null default '',
  "cliente_nombre" text not null default '',
  "mascota" text not null default '',
  "pregunta" text not null default '',
  "estado" text not null default 'pendiente',
  "fecha_creacion" text not null default '',
  "fecha_respuesta" text not null default ''
);
alter table "relay_retiro" enable row level security;
create index if not exists "relay_retiro_admin_msg_id_idx" on "relay_retiro" ("admin_msg_id");

-- ── Módulo "Estado de Resultados" (EERR) ─────────────────────────────────────
-- Estructura (sin seed). El seed de partidas + migración para entornos existentes
-- vive en supabase/eerr-schema.sql.
create table if not exists "eerr_partidas" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',
  "nombre" text not null default '',
  "clave" text not null default '',
  "orden" text not null default '',
  "activo" text not null default 'TRUE',
  "fecha_creacion" text not null default '',
  "subgrupo_id" text not null default '',
  constraint "eerr_partidas_tipo_nombre_uniq" unique ("tipo", "nombre")
);
alter table "eerr_partidas" enable row level security;
alter table "eerr_partidas" add column if not exists "subgrupo_id" text not null default '';

create table if not exists "eerr_subgrupos" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',
  "nombre" text not null default '',
  "orden" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_subgrupos_tipo_nombre_uniq" unique ("tipo", "nombre")
);
alter table "eerr_subgrupos" enable row level security;

create table if not exists "eerr_proveedores" (
  "id" bigint generated by default as identity primary key,
  "rut" text not null default '',
  "razon_social" text not null default '',
  "auto_contabiliza" text not null default 'FALSE',
  "auto_tipo" text not null default '',
  "auto_partida_id" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_proveedores_rut_uniq" unique ("rut")
);
alter table "eerr_proveedores" enable row level security;

create table if not exists "eerr_gastos_sii" (
  "id" bigint generated by default as identity primary key,
  "tipo_doc" text not null default '',
  "tipo_compra" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "folio" text not null default '',
  "fecha_documento" text not null default '',
  "fecha_recepcion" text not null default '',
  "monto_exento" text not null default '',
  "monto_neto" text not null default '',
  "monto_iva" text not null default '',
  "monto_total" text not null default '',
  "valor_otro_impuesto" text not null default '',
  "comentario" text not null default '',
  "tipo_asignacion" text not null default '',
  "partida_id" text not null default '',
  "contabilizado" text not null default 'FALSE',
  "fecha_carga" text not null default '',
  "fecha_creacion" text not null default '',
  constraint "eerr_gastos_sii_dedup_uniq" unique ("rut", "tipo_doc", "folio")
);
alter table "eerr_gastos_sii" enable row level security;
create index if not exists "eerr_gastos_sii_fecha_idx" on "eerr_gastos_sii" ("fecha_documento");
create index if not exists "eerr_gastos_sii_partida_idx" on "eerr_gastos_sii" ("partida_id");

create table if not exists "eerr_gastos_manuales" (
  "id" bigint generated by default as identity primary key,
  "tipo_asignacion" text not null default '',
  "partida_id" text not null default '',
  "detalle" text not null default '',
  "monto" text not null default '',
  "fecha" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_gastos_manuales" enable row level security;
create index if not exists "eerr_gastos_manuales_fecha_idx" on "eerr_gastos_manuales" ("fecha");

alter table "rendiciones" add column if not exists "partida_id" text not null default '';
alter table "rendiciones" add column if not exists "clasificacion" text not null default 'rendicion';

-- ── Marketing: calendario de campañas multicanal + config del agente ──────────
-- Calendario de campañas (email | instagram | facebook). Capa de planificación
-- que alimenta el agente de marketing. estado: propuesta → aprobada → generada →
-- programada → publicada | descartada. El email aprobado puede materializarse en
-- mailing_campanas; el social se publica vía Meta Graph API (post_externo_id/url).
create table if not exists "campaign_calendar" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "hora" text not null default '',
  "canal" text not null default '',
  "estado" text not null default 'propuesta',
  "activa" text not null default 'TRUE',
  "favorita" text not null default 'FALSE',
  "objetivo" text not null default '',
  "audiencia" text not null default '',
  "idea" text not null default '',
  "titulo" text not null default '',
  "cuerpo" text not null default '',
  "imagen_id" text not null default '',
  "imagen_url" text not null default '',
  "imagenes_json" text not null default '',
  "estilo" text not null default '',
  "campana_id" text not null default '',
  "post_externo_id" text not null default '',
  "post_url" text not null default '',
  "estado_publicacion" text not null default '',
  "error_publicacion" text not null default '',
  "generado_por" text not null default 'ia',
  "aprobado_por" text not null default '',
  "fecha_publicacion" text not null default '',
  "notas" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "campaign_calendar" enable row level security;
create index if not exists "campaign_calendar_fecha_idx" on "campaign_calendar" ("fecha");
create index if not exists "campaign_calendar_estado_idx" on "campaign_calendar" ("estado");
alter table "campaign_calendar" add column if not exists "imagenes_json" text not null default '';
alter table "campaign_calendar" add column if not exists "activa" text not null default 'TRUE';
alter table "campaign_calendar" add column if not exists "hora" text not null default '';
alter table "campaign_calendar" add column if not exists "favorita" text not null default 'FALSE';
-- Memoria de variedad del generador de piezas (JSON {portada, fondos[], fotos[]}).
alter table "campaign_calendar" add column if not exists "estilo" text not null default '';

-- Config editable del agente de marketing (una sola fila, id=1).
create table if not exists "marketing_config" (
  "id" bigint generated by default as identity primary key,
  "instrucciones" text not null default '',
  "calibracion" text not null default '',
  "parametros" text not null default '',
  "updated_at" text not null default ''
);
-- parametros: JSON editable con la cadencia, los pilares editoriales y (para ads)
-- CPA/CPL/presupuesto. Lo lee lib/marketing-params.ts (getMarketingParams).
alter table "marketing_config" add column if not exists "parametros" text not null default '';
alter table "marketing_config" enable row level security;

-- Bitácora de decisiones de marketing (lib/marketing-decisiones.ts): registro
-- automático de toda ESCRITURA aprobada que ejecuta el agente (Google Ads: pausas,
-- presupuestos, negativas, RSAs, campañas; Meta: publicar, perfil). Acceso directo
-- por getSupabase() (no datastore), como mailing_logs/correos_log.
create table if not exists marketing_decisiones (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  area        text not null default '',   -- google_ads | meta | contenido
  accion      text not null default '',   -- ej. pausar_campana, presupuesto, negativas_lote, crear_rsa, crear_campana, publicar_pieza
  detalle     text not null default '',   -- qué cambió exactamente (campaña/keyword, antes → después, montos)
  motivo      text not null default '',   -- por qué se hizo (lo aporta el agente al ejecutar)
  resultado   text not null default '',   -- resultado inmediato reportado por la herramienta
  aprobado_por text not null default ''   -- usuario del chat que confirmó la acción
);
create index if not exists idx_mkdec_created on marketing_decisiones(created_at desc);
alter table marketing_decisiones enable row level security;

-- Permisos dinámicos por módulo × rol (editable en Configuración Avanzada → Usuarios).
-- Solo overrides de admin2/operador; lo no listado usa el default de lib/permisos.ts.
create table if not exists "permisos_modulos" (
  "modulo" text not null,
  "rol" text not null,
  "permitido" text not null default 'FALSE',
  "updated_at" text not null default '',
  primary key ("modulo", "rol")
);
alter table "permisos_modulos" enable row level security;
