-- Esquema principal (Sheets → Postgres). GENERADO por scripts/generar-schema-sql.ts
-- Correr en el SQL editor del proyecto Supabase de mailing (SUPABASE_URL).
-- Columnas en text (drop-in); id como identity. Ver docs/migracion-postgres.md.

-- getNextId atómico (reemplaza el max(id)+1 con race de Sheets)
create or replace function next_id(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select nextval(%L)', seq) into v;
  return v;
end $$;

-- Ajusta el sequence de id al max(id) actual (correr tras el import)
create or replace function reset_id_seq(p_table text)
returns bigint language plpgsql as $$
declare seq text; v bigint;
begin
  seq := pg_get_serial_sequence(p_table, 'id');
  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;
  execute format('select coalesce(max(id),0) from %I', p_table) into v;
  perform setval(seq, greatest(v, 1), v > 0);
  return v;
end $$;

create table if not exists "clientes" (
  "id" bigint generated by default as identity primary key,
  "codigo" text not null default '',
  "nombre_mascota" text not null default '',
  "nombre_tutor" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "direccion_retiro" text not null default '',
  "direccion_despacho" text not null default '',
  "misma_direccion" text not null default '',
  "depto" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "hora_retiro" text not null default '',
  "fecha_defuncion" text not null default '',
  "fecha_nacimiento" text not null default '',
  "especie" text not null default '',
  "letra_especie" text not null default '',
  "peso_declarado" text not null default '',
  "peso_ingreso" text not null default '',
  "tipo_servicio" text not null default '',
  "codigo_servicio" text not null default '',
  "estado" text not null default '',
  "ciclo_id" text not null default '',
  "despacho_id" text not null default '',
  "veterinaria_id" text not null default '',
  "tipo_precios" text not null default '',
  "adicionales" text not null default '',
  "descuento_id" text not null default '',
  "descuento_nombre" text not null default '',
  "descuento_tipo" text not null default '',
  "descuento_valor" text not null default '',
  "descuento_monto" text not null default '',
  "precio_servicio" text not null default '',
  "precio_adicionales" text not null default '',
  "precio_total" text not null default '',
  "notas" text not null default '',
  "tipo_pago" text not null default '',
  "estado_pago" text not null default '',
  "omitir_evaluacion" text not null default '',
  "fotos_mascota" text not null default '',
  "fotos_cuadro" text not null default '',
  "videos_servicio" text not null default '',
  "video_solicitado" text not null default '',
  "fotos_evidencia" text not null default '',
  "correo_diferencia_fecha" text not null default '',
  "correo_diferencia_monto" text not null default '',
  "factura_vet_id" text not null default '',
  "boleta_id" text not null default '',
  "greda_descontada" text not null default '',
  "origen" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "clientes" enable row level security;
create index if not exists "clientes_estado_idx" on "clientes" ("estado");
create index if not exists "clientes_codigo_idx" on "clientes" ("codigo");
create index if not exists "clientes_ciclo_id_idx" on "clientes" ("ciclo_id");
create index if not exists "clientes_despacho_id_idx" on "clientes" ("despacho_id");
create index if not exists "clientes_veterinaria_id_idx" on "clientes" ("veterinaria_id");

create table if not exists "ciclos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_ciclo" text not null default '',
  "litros_inicio" text not null default '',
  "litros_fin" text not null default '',
  "mascotas_ids" text not null default '',
  "comentarios" text not null default '',
  "hora_inicio" text not null default '',
  "hora_fin" text not null default '',
  "temperatura_camara" text not null default '',
  "peso_total" text not null default '',
  "lt_kg" text not null default '',
  "lt_mascota" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "ciclos" enable row level security;
create index if not exists "ciclos_fecha_idx" on "ciclos" ("fecha");

create table if not exists "cargas_petroleo" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "precio_neto" text not null default '',
  "iva" text not null default '',
  "especifico" text not null default '',
  "total_bruto" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "cargas_petroleo" enable row level security;

create table if not exists "vehiculo_cargas" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "litros" text not null default '',
  "km_odometro" text not null default '',
  "monto" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vehiculo_cargas" enable row level security;

create table if not exists "despachos" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "numero_recorrido" text not null default '',
  "numero_global" text not null default '',
  "mascotas_ids" text not null default '',
  "nota" text not null default '',
  "fecha_creacion" text not null default '',
  "estado_ruta" text not null default '',
  "origen_direccion" text not null default '',
  "origen_lat" text not null default '',
  "origen_lng" text not null default '',
  "destino_direccion" text not null default '',
  "destino_lat" text not null default '',
  "destino_lng" text not null default '',
  "paradas" text not null default '',
  "entregas" text not null default '',
  "hora_inicio_ruta" text not null default '',
  "hora_termino_ruta" text not null default '',
  "fecha_realizada" text not null default ''
);
alter table "despachos" enable row level security;
create index if not exists "despachos_estado_ruta_idx" on "despachos" ("estado_ruta");

create table if not exists "rendiciones" (
  "id" bigint generated by default as identity primary key,
  "usuario" text not null default '',
  "descripcion" text not null default '',
  "fecha" text not null default '',
  "monto" text not null default '',
  "tipo_documento" text not null default '',
  "partida_id" text not null default '',
  "clasificacion" text not null default '',
  "estado" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rendiciones" enable row level security;

create table if not exists "pagos_rendicion" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_pagado" text not null default '',
  "rendicion_ids" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_rendicion" enable row level security;

create table if not exists "veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "nombre_contacto" text not null default '',
  "cargo_contacto" text not null default '',
  "tipo_precios" text not null default '',
  "precios_especiales" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default '',
  "precios_indexados" text not null default ''
);
alter table "veterinarios" enable row level security;

create table if not exists "precios_generales" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_generales" enable row level security;

create table if not exists "precios_convenio" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_convenio" enable row level security;

create table if not exists "precios_especiales" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio_ci" text not null default '',
  "precio_cp" text not null default '',
  "precio_sd" text not null default ''
);
alter table "precios_especiales" enable row level security;

create table if not exists "productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "categoria" text not null default '',
  "precio" text not null default '',
  "foto_url" text not null default '',
  "stock" text not null default '',
  "activo" text not null default '',
  "mostrar_web" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "productos" enable row level security;

create table if not exists "categorias_productos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "categorias_productos" enable row level security;

create table if not exists "informes_veterinaria" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "veterinaria_nombre" text not null default '',
  "version" text not null default '',
  "formato" text not null default '',
  "periodo_hasta_mes" text not null default '',
  "cantidad_meses" text not null default '',
  "cantidad_fichas" text not null default '',
  "monto_total_clp" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "archivo_key" text not null default '',
  "archivo_url" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "informes_veterinaria" enable row level security;

create table if not exists "especies" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "letra" text not null default '',
  "activo" text not null default ''
);
alter table "especies" enable row level security;

create table if not exists "tipos_servicio" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "codigo" text not null default '',
  "plazo_entrega_dias" text not null default '',
  "activo" text not null default ''
);
alter table "tipos_servicio" enable row level security;

create table if not exists "otros_servicios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "precio" text not null default '',
  "activo" text not null default '',
  "auto_regla" text not null default '',
  "comunas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "otros_servicios" enable row level security;

create table if not exists "cobros" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "tipo" text not null default '',
  "detalle" text not null default '',
  "monto" text not null default '',
  "estado" text not null default '',
  "message_id" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_cliente_confirmo" text not null default '',
  "fecha_pagado" text not null default '',
  "boleta_id" text not null default ''
);
alter table "cobros" enable row level security;

create table if not exists "descuentos" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "tipo" text not null default '',
  "valor" text not null default '',
  "activo" text not null default '',
  "foto_url" text not null default '',
  "mostrar_web" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "descuentos" enable row level security;

create table if not exists "comisiones_reglas" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "tipo" text not null default '',
  "valor" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "comisiones_reglas" enable row level security;

create table if not exists "comisiones" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "cliente_id" text not null default '',
  "documento_id" text not null default '',
  "base_monto" text not null default '',
  "tipo" text not null default '',
  "valor" text not null default '',
  "monto" text not null default '',
  "estado" text not null default '',
  "fecha_devengo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "comisiones" enable row level security;

create table if not exists "comisiones_ajustes" (
  "id" bigint generated by default as identity primary key,
  "veterinaria_id" text not null default '',
  "monto" text not null default '',
  "detalle" text not null default '',
  "fecha" text not null default '',
  "gasto_manual_id" text not null default '',
  "creado_por_id" text not null default '',
  "creado_por_nombre" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "comisiones_ajustes" enable row level security;

create table if not exists "usuarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "password" text not null default '',
  "rol" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default '',
  "telefono" text not null default '',
  "avisos_whatsapp" text not null default '',
  "perfil_id" text not null default ''
);
alter table "usuarios" enable row level security;

create table if not exists "asistencia" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "dia_semana" text not null default '',
  "es_findesemana" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "minutos_trabajados" text not null default '',
  "minutos_normales" text not null default '',
  "minutos_extra" text not null default '',
  "estado_aprobacion" text not null default '',
  "aprobado_por" text not null default '',
  "comentario" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "asistencia" enable row level security;
create index if not exists "asistencia_fecha_idx" on "asistencia" ("fecha");

create table if not exists "jornada_config" (
  "id" bigint generated by default as identity primary key,
  "vigente_desde" text not null default '',
  "hora_entrada" text not null default '',
  "hora_salida" text not null default '',
  "precio_hora_extra" text not null default '',
  "tolerancia_minutos" text not null default '',
  "precio_retiro_adicional" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "jornada_config" enable row level security;

create table if not exists "retiros_adicionales" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "fecha" text not null default '',
  "hora" text not null default '',
  "cliente_nombre" text not null default '',
  "comentario" text not null default '',
  "pago_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "retiros_adicionales" enable row level security;

create table if not exists "pagos_retiros" (
  "id" bigint generated by default as identity primary key,
  "fecha_pago" text not null default '',
  "usuario_id" text not null default '',
  "usuario_nombre" text not null default '',
  "retiros_ids" text not null default '',
  "cantidad" text not null default '',
  "monto_total" text not null default '',
  "comentarios" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "pagos_retiros" enable row level security;

create table if not exists "certificados" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "codigo_mascota" text not null default '',
  "nombre_mascota" text not null default '',
  "version" text not null default '',
  "fecha_emision" text not null default '',
  "hora_emision" text not null default '',
  "emitido_por_id" text not null default '',
  "emitido_por_nombre" text not null default '',
  "sin_foto" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "enviado_ultima_fecha" text not null default '',
  "enviado_ultima_hora" text not null default '',
  "enviado_cantidad" text not null default '',
  "enviado_a" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "certificados" enable row level security;
create index if not exists "certificados_cliente_id_idx" on "certificados" ("cliente_id");

create table if not exists "documentos_tributarios" (
  "id" bigint generated by default as identity primary key,
  "tipo_dte" text not null default '',
  "folio" text not null default '',
  "estado" text not null default '',
  "ambiente" text not null default '',
  "fecha_emision" text not null default '',
  "receptor_tipo" text not null default '',
  "receptor_id" text not null default '',
  "receptor_rut" text not null default '',
  "receptor_razon_social" text not null default '',
  "receptor_giro" text not null default '',
  "receptor_direccion" text not null default '',
  "receptor_comuna" text not null default '',
  "receptor_correo" text not null default '',
  "monto_neto" text not null default '',
  "monto_iva" text not null default '',
  "monto_total" text not null default '',
  "detalle_json" text not null default '',
  "resumen" text not null default '',
  "mes_facturado" text not null default '',
  "fichas_json" text not null default '',
  "openfactura_url" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "documento_anulado_id" text not null default '',
  "nc_id" text not null default '',
  "motivo_anulacion" text not null default '',
  "warnings_json" text not null default '',
  "creado_por_id" text not null default '',
  "creado_por_nombre" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "documentos_tributarios" enable row level security;

create table if not exists "geocoding_cache" (
  "id" bigint generated by default as identity primary key,
  "direccion_normalizada" text not null default '',
  "direccion_original" text not null default '',
  "lat" text not null default '',
  "lng" text not null default '',
  "formatted_address" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "geocoding_cache" enable row level security;

create table if not exists "empresa_config" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "rut" text not null default '',
  "giro" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "correo" text not null default '',
  "web" text not null default '',
  "instagram" text not null default '',
  "facebook" text not null default '',
  "google_review_url" text not null default '',
  "email_seguimiento" text not null default '',
  "email_seguimiento_activo" text not null default '',
  "seguimiento_tipos" text not null default '',
  "titular_cuenta" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "empresa_config" enable row level security;

create table if not exists "mailing_veterinarios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "email" text not null default '',
  "veterinaria" text not null default '',
  "comuna" text not null default '',
  "telefono" text not null default '',
  "categoria" text not null default '',
  "tamano_veterinaria" text not null default '',
  "suscrito" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_veterinarios" enable row level security;
create index if not exists "mailing_veterinarios_email_idx" on "mailing_veterinarios" ("email");

create table if not exists "mailing_campanas" (
  "id" bigint generated by default as identity primary key,
  "asunto" text not null default '',
  "html_key" text not null default '',
  "html_url" text not null default '',
  "preview_text" text not null default '',
  "reply_to" text not null default '',
  "fecha_envio" text not null default '',
  "hora_envio" text not null default '',
  "total_destinatarios" text not null default '',
  "enviados" text not null default '',
  "entregados" text not null default '',
  "aperturas" text not null default '',
  "clicks" text not null default '',
  "rebotes" text not null default '',
  "spam" text not null default '',
  "fallidos" text not null default '',
  "estado" text not null default '',
  "filtros_json" text not null default '',
  "attachments_json" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_campanas" enable row level security;

create table if not exists "correos_cliente" (
  "id" bigint generated by default as identity primary key,
  "cliente_id" text not null default '',
  "tipo" text not null default '',
  "email" text not null default '',
  "message_id" text not null default '',
  "estado" text not null default '',
  "motivo" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "correos_cliente" enable row level security;

create table if not exists "correos_log" (
  "id" bigint generated by default as identity primary key,
  "fecha_envio" text not null default '',
  "tipo" text not null default '',
  "audiencia" text not null default '',
  "destinatario" text not null default '',
  "asunto" text not null default '',
  "cliente_id" text not null default '',
  "codigo" text not null default '',
  "nombre" text not null default '',
  "message_id" text not null default '',
  "estado" text not null default '',
  "motivo" text not null default '',
  "html" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "correos_log" enable row level security;

create table if not exists "mailing_imagenes" (
  "id" bigint generated by default as identity primary key,
  "url" text not null default '',
  "key" text not null default '',
  "codigo" text not null default '',
  "descripcion" text not null default '',
  "prompt" text not null default '',
  "tags" text not null default '',
  "alt" text not null default '',
  "grupo" text not null default '',
  "subgrupo" text not null default '',
  "whatsapp" text not null default '',
  "favorita" text not null default '',
  "aspect" text not null default '',
  "ancho" text not null default '',
  "alto" text not null default '',
  "origen" text not null default '',
  "modelo" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_imagenes" enable row level security;

create table if not exists "mailing_videos" (
  "id" bigint generated by default as identity primary key,
  "url" text not null default '',
  "key" text not null default '',
  "codigo" text not null default '',
  "descripcion" text not null default '',
  "prompt" text not null default '',
  "imagen_origen" text not null default '',
  "aspect" text not null default '',
  "duracion" text not null default '',
  "modelo" text not null default '',
  "favorita" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "mailing_videos" enable row level security;

create table if not exists "campaign_calendar" (
  "id" bigint generated by default as identity primary key,
  "fecha" text not null default '',
  "hora" text not null default '',
  "canal" text not null default '',
  "estado" text not null default '',
  "activa" text not null default '',
  "favorita" text not null default '',
  "objetivo" text not null default '',
  "audiencia" text not null default '',
  "idea" text not null default '',
  "titulo" text not null default '',
  "cuerpo" text not null default '',
  "imagen_id" text not null default '',
  "imagen_url" text not null default '',
  "imagenes_json" text not null default '',
  "estilo" text not null default '',
  "campana_id" text not null default '',
  "post_externo_id" text not null default '',
  "post_url" text not null default '',
  "estado_publicacion" text not null default '',
  "error_publicacion" text not null default '',
  "generado_por" text not null default '',
  "aprobado_por" text not null default '',
  "fecha_publicacion" text not null default '',
  "notas" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "campaign_calendar" enable row level security;

create table if not exists "marketing_config" (
  "id" bigint generated by default as identity primary key,
  "instrucciones" text not null default '',
  "calibracion" text not null default '',
  "parametros" text not null default '',
  "updated_at" text not null default ''
);
alter table "marketing_config" enable row level security;

create table if not exists "vet_convenio_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "apellido" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "rut" text not null default '',
  "comunas" text not null default '',
  "horarios" text not null default '',
  "activo" text not null default '',
  "origen" text not null default '',
  "notas" text not null default '',
  "total_servicios" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "datos_pago_completos" text not null default '',
  "fecha_datos_pago" text not null default '',
  "fecha_inscripcion" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "vet_convenio_eutanasia" enable row level security;

create table if not exists "precios_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "peso_min" text not null default '',
  "peso_max" text not null default '',
  "precio" text not null default ''
);
alter table "precios_eutanasia" enable row level security;

create table if not exists "config_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "fijo" text not null default '',
  "consulta_vet" text not null default '',
  "consulta_alma" text not null default '',
  "recargo_fuera_horario" text not null default ''
);
alter table "config_eutanasia" enable row level security;

create table if not exists "cotizaciones_eutanasia" (
  "id" bigint generated by default as identity primary key,
  "mascota_nombre" text not null default '',
  "especie" text not null default '',
  "peso" text not null default '',
  "cliente_nombre" text not null default '',
  "cliente_telefono" text not null default '',
  "cliente_email" text not null default '',
  "cliente_wa_id" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_servicio" text not null default '',
  "hora_servicio" text not null default '',
  "hora_retiro_crematorio" text not null default '',
  "tipo_servicio_cremacion" text not null default '',
  "incluye_cremacion" text not null default '',
  "notas" text not null default '',
  "estado" text not null default '',
  "vet_id_asignado" text not null default '',
  "vet_nombre_asignado" text not null default '',
  "vet_email_asignado" text not null default '',
  "precio_snapshot" text not null default '',
  "consulta_vet_snapshot" text not null default '',
  "cliente_id" text not null default '',
  "estado_pago" text not null default '',
  "fecha_pago" text not null default '',
  "cliente_confirmo" text not null default '',
  "fecha_cliente_confirmacion" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_envio_cotizacion" text not null default '',
  "fecha_aceptacion" text not null default '',
  "fecha_confirmacion" text not null default '',
  "fecha_realizacion" text not null default '',
  "fecha_cancelacion" text not null default '',
  "creado_por" text not null default ''
);
alter table "cotizaciones_eutanasia" enable row level security;
create index if not exists "cotizaciones_eutanasia_estado_idx" on "cotizaciones_eutanasia" ("estado");
create index if not exists "cotizaciones_eutanasia_vet_id_asignado_idx" on "cotizaciones_eutanasia" ("vet_id_asignado");

create table if not exists "cotizaciones_eutanasia_envios" (
  "id" bigint generated by default as identity primary key,
  "cotizacion_id" text not null default '',
  "vet_id" text not null default '',
  "vet_email" text not null default '',
  "fecha_envio" text not null default '',
  "fecha_respuesta" text not null default '',
  "estado_envio" text not null default '',
  "resend_message_id" text not null default ''
);
alter table "cotizaciones_eutanasia_envios" enable row level security;
create index if not exists "cotizaciones_eutanasia_envios_cotizacion_id_idx" on "cotizaciones_eutanasia_envios" ("cotizacion_id");
create index if not exists "cotizaciones_eutanasia_envios_vet_id_idx" on "cotizaciones_eutanasia_envios" ("vet_id");

create table if not exists "solicitudes_retiro" (
  "id" bigint generated by default as identity primary key,
  "cliente_wa_id" text not null default '',
  "cliente_nombre" text not null default '',
  "nombre_mascota" text not null default '',
  "peso" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "fecha_retiro" text not null default '',
  "hora_retiro" text not null default '',
  "tipo_servicio" text not null default '',
  "estado" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_resolucion" text not null default '',
  "origen" text not null default '',
  "veterinaria_id" text not null default '',
  "vet_nombre" text not null default '',
  "vet_email" text not null default '',
  "cliente_id" text not null default ''
);
alter table "solicitudes_retiro" enable row level security;
create index if not exists "solicitudes_retiro_estado_idx" on "solicitudes_retiro" ("estado");
create index if not exists "solicitudes_retiro_cliente_wa_id_idx" on "solicitudes_retiro" ("cliente_wa_id");

create table if not exists "relay_retiro" (
  "id" bigint generated by default as identity primary key,
  "admin_msg_id" text not null default '',
  "cliente_wa_id" text not null default '',
  "cliente_nombre" text not null default '',
  "mascota" text not null default '',
  "pregunta" text not null default '',
  "estado" text not null default '',
  "fecha_creacion" text not null default '',
  "fecha_respuesta" text not null default ''
);
alter table "relay_retiro" enable row level security;

create table if not exists "agenda_bloqueos" (
  "id" bigint generated by default as identity primary key,
  "fecha_inicio" text not null default '',
  "hora_inicio" text not null default '',
  "fecha_fin" text not null default '',
  "hora_fin" text not null default '',
  "motivo" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default '',
  "activo" text not null default ''
);
alter table "agenda_bloqueos" enable row level security;

create table if not exists "eerr_partidas" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',
  "nombre" text not null default '',
  "clave" text not null default '',
  "orden" text not null default '',
  "subgrupo_id" text not null default '',
  "activo" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_partidas" enable row level security;

create table if not exists "eerr_subgrupos" (
  "id" bigint generated by default as identity primary key,
  "tipo" text not null default '',
  "nombre" text not null default '',
  "orden" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_subgrupos" enable row level security;

create table if not exists "eerr_proveedores" (
  "id" bigint generated by default as identity primary key,
  "rut" text not null default '',
  "razon_social" text not null default '',
  "auto_contabiliza" text not null default '',
  "auto_tipo" text not null default '',
  "auto_partida_id" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_proveedores" enable row level security;

create table if not exists "eerr_gastos_sii" (
  "id" bigint generated by default as identity primary key,
  "tipo_doc" text not null default '',
  "tipo_compra" text not null default '',
  "rut" text not null default '',
  "razon_social" text not null default '',
  "folio" text not null default '',
  "fecha_documento" text not null default '',
  "fecha_recepcion" text not null default '',
  "monto_exento" text not null default '',
  "monto_neto" text not null default '',
  "monto_iva" text not null default '',
  "monto_total" text not null default '',
  "valor_otro_impuesto" text not null default '',
  "comentario" text not null default '',
  "tipo_asignacion" text not null default '',
  "partida_id" text not null default '',
  "contabilizado" text not null default '',
  "fecha_carga" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_gastos_sii" enable row level security;

create table if not exists "eerr_gastos_manuales" (
  "id" bigint generated by default as identity primary key,
  "tipo_asignacion" text not null default '',
  "partida_id" text not null default '',
  "detalle" text not null default '',
  "monto" text not null default '',
  "fecha" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "eerr_gastos_manuales" enable row level security;

create table if not exists "web_servicios" (
  "id" bigint generated by default as identity primary key,
  "nombre" text not null default '',
  "slug" text not null default '',
  "resumen" text not null default '',
  "descripcion" text not null default '',
  "foto_url" text not null default '',
  "precio_desde" text not null default '',
  "orden" text not null default '',
  "publicado" text not null default '',
  "seo_titulo" text not null default '',
  "seo_desc" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_servicios" enable row level security;

create table if not exists "web_posts" (
  "id" bigint generated by default as identity primary key,
  "titulo" text not null default '',
  "slug" text not null default '',
  "categoria" text not null default '',
  "extracto" text not null default '',
  "contenido" text not null default '',
  "foto_url" text not null default '',
  "autor" text not null default '',
  "fecha" text not null default '',
  "publicado" text not null default '',
  "seo_titulo" text not null default '',
  "seo_desc" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_posts" enable row level security;

create table if not exists "web_paginas" (
  "id" bigint generated by default as identity primary key,
  "pagina" text not null default '',
  "clave" text not null default '',
  "titulo" text not null default '',
  "contenido" text not null default '',
  "foto_url" text not null default '',
  "orden" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "web_paginas" enable row level security;

create table if not exists "avisos_config" (
  "id" bigint generated by default as identity primary key,
  "clave" text not null default '',
  "activo" text not null default '',
  "destinatarios" text not null default '',
  "hora" text not null default '',
  "omitir_vacio" text not null default '',
  "ultimo_envio" text not null default '',
  "fecha_actualizacion" text not null default ''
);
alter table "avisos_config" enable row level security;

create table if not exists "rrhh_empleados" (
  "id" bigint generated by default as identity primary key,
  "usuario_id" text not null default '',
  "nombre_completo" text not null default '',
  "rut" text not null default '',
  "fecha_nacimiento" text not null default '',
  "nacionalidad" text not null default '',
  "direccion" text not null default '',
  "comuna" text not null default '',
  "email" text not null default '',
  "telefono" text not null default '',
  "cargo" text not null default '',
  "unidad_negocio" text not null default '',
  "tipo_contrato" text not null default '',
  "fecha_ingreso" text not null default '',
  "fecha_termino" text not null default '',
  "jornada_semanal_horas" text not null default '',
  "sueldo_base" text not null default '',
  "modalidad_variable" text not null default '',
  "valor_por_cremacion" text not null default '',
  "haberes_no_imponibles" text not null default '',
  "afp" text not null default '',
  "prevision_salud" text not null default '',
  "isapre_codigo" text not null default '',
  "plan_salud_uf" text not null default '',
  "apv_monto" text not null default '',
  "apv_institucion" text not null default '',
  "banco" text not null default '',
  "tipo_cuenta" text not null default '',
  "numero_cuenta" text not null default '',
  "activo" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_empleados" enable row level security;

create table if not exists "rrhh_parametros" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',
  "valor_uf" text not null default '',
  "valor_utm" text not null default '',
  "imm" text not null default '',
  "tope_afp_uf" text not null default '',
  "tope_afc_uf" text not null default '',
  "tasas_afp" text not null default '',
  "tramos_impuesto" text not null default '',
  "tasa_afc_trabajador" text not null default '',
  "tasa_afc_empleador_indefinido" text not null default '',
  "tasa_afc_empleador_plazo_fijo" text not null default '',
  "tasa_mutual" text not null default '',
  "tasa_sis" text not null default '',
  "tasa_cuenta_individual" text not null default '',
  "tasa_fapp" text not null default '',
  "tasa_seguro_social" text not null default '',
  "factor_gratificacion" text not null default '',
  "tope_gratificacion_imm" text not null default '',
  "dias_habiles" text not null default '',
  "dias_descanso" text not null default '',
  "notas" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_parametros" enable row level security;
create index if not exists "rrhh_parametros_periodo_idx" on "rrhh_parametros" ("periodo");

create table if not exists "rrhh_liquidaciones" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',
  "empleado_id" text not null default '',
  "empleado_nombre" text not null default '',
  "estado" text not null default '',
  "cremaciones" text not null default '',
  "meta_liquido" text not null default '',
  "variable_imponible" text not null default '',
  "total_imponible" text not null default '',
  "total_no_imponible" text not null default '',
  "total_haberes" text not null default '',
  "total_descuentos" text not null default '',
  "impuesto_unico" text not null default '',
  "liquido" text not null default '',
  "reembolso_salud" text not null default '',
  "total_a_transferir" text not null default '',
  "aportes_empleador" text not null default '',
  "costo_empresa" text not null default '',
  "exacto" text not null default '',
  "diferencia_meta" text not null default '',
  "detalle_json" text not null default '',
  "parametros_json" text not null default '',
  "novedades_json" text not null default '',
  "pdf_key" text not null default '',
  "pdf_url" text not null default '',
  "fecha_pago" text not null default '',
  "cerrada_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_liquidaciones" enable row level security;
create index if not exists "rrhh_liquidaciones_periodo_idx" on "rrhh_liquidaciones" ("periodo");
create index if not exists "rrhh_liquidaciones_empleado_id_idx" on "rrhh_liquidaciones" ("empleado_id");

create table if not exists "rrhh_pagos" (
  "id" bigint generated by default as identity primary key,
  "periodo" text not null default '',
  "liquidacion_ids" text not null default '',
  "total_liquidos" text not null default '',
  "total_reembolsos" text not null default '',
  "total_transferido" text not null default '',
  "costo_empresa" text not null default '',
  "fecha_pago" text not null default '',
  "comentarios" text not null default '',
  "creado_por" text not null default '',
  "fecha_creacion" text not null default ''
);
alter table "rrhh_pagos" enable row level security;
create index if not exists "rrhh_pagos_periodo_idx" on "rrhh_pagos" ("periodo");

-- ════════════════════════════════════════════════════════════════════════════
--  Tablas EXTRA del esquema principal.
--
--  Todo lo de acá NO sale del mapa `SHEETS` (lib/sheets-schema.ts) porque no se
--  accede por `datastore`: son logs y tablas de sistema que usan `getSupabase()`
--  directo. El generador (scripts/generar-schema-sql.ts) las APENDEA al final de
--  supabase/schema-principal.sql — antes vivían pegadas a mano en ese archivo y
--  se PERDÍAN en cada regeneración.
--
--  Al sumar una tabla que no va por datastore, agregarla acá (no al .sql generado).
-- ════════════════════════════════════════════════════════════════════════════

-- Rate limiting de login (NextAuth Credentials, lib/auth.ts vía lib/login-rate-limit.ts):
-- una fila por intento FALLIDO (email+IP). 5 fallidos en 15 min → bloqueado. Fail-open
-- si Supabase falla (un rate limit caído no debe tumbar el acceso).
create table if not exists "login_intentos" (
  "id" bigint generated by default as identity primary key,
  "email" text not null default '',
  "ip" text not null default '',
  "creado_en" text not null default ''
);
alter table "login_intentos" enable row level security;
create index if not exists "login_intentos_email_ip_idx" on "login_intentos" ("email", "ip", "creado_en");
create index if not exists "correos_log_message_id_idx" on "correos_log" ("message_id");

-- Bitácora de decisiones de marketing (lib/marketing-decisiones.ts): registro
-- automático de toda ESCRITURA aprobada que ejecuta el agente (Google Ads: pausas,
-- presupuestos, negativas, RSAs, campañas; Meta: publicar, perfil). Acceso directo
-- por getSupabase() (no datastore), como mailing_logs/correos_log.
create table if not exists marketing_decisiones (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  area        text not null default '',   -- google_ads | meta | contenido
  accion      text not null default '',   -- ej. pausar_campana, presupuesto, negativas_lote, crear_rsa, crear_campana, publicar_pieza
  detalle     text not null default '',   -- qué cambió exactamente (campaña/keyword, antes → después, montos)
  motivo      text not null default '',   -- por qué se hizo (lo aporta el agente al ejecutar)
  resultado   text not null default '',   -- resultado inmediato reportado por la herramienta
  aprobado_por text not null default ''   -- usuario del chat que confirmó la acción
);
create index if not exists idx_mkdec_created on marketing_decisiones(created_at desc);
alter table marketing_decisiones enable row level security;

-- Permisos dinámicos por módulo × rol (editable en Configuración Avanzada → Usuarios).
-- Solo overrides de admin2/operador; lo no listado usa el default de lib/permisos.ts.
create table if not exists "permisos_modulos" (
  "modulo" text not null,
  "rol" text not null,
  "permitido" text not null default 'FALSE',
  "updated_at" text not null default '',
  primary key ("modulo", "rol")
);
alter table "permisos_modulos" enable row level security;

-- Consumo de IA: una fila por llamada a un modelo (Claude) o generación de
-- imagen/video (Gemini). La escribe lib/uso-ia (best-effort) desde cada módulo
-- que consume IA; la lee Configuración Avanzada → Consumo IA. El costo es una
-- ESTIMACIÓN con la tabla de precios de lib/uso-ia, no la factura del proveedor.
-- Acceso directo por getSupabase() (no datastore: es un log, no una entidad).
create table if not exists uso_ia (
  id              bigint generated always as identity primary key,
  created_at      timestamptz not null default now(),
  fecha           text not null default '',   -- YYYY-MM-DD (Chile)
  ts              text not null default '',   -- ISO completo
  modulo          text not null default '',   -- bot-inbox | marketing-chat | imagen | ...
  modelo          text not null default '',
  entrada         bigint not null default 0,  -- input tokens NO cacheados
  salida          bigint not null default 0,
  cache_lectura   bigint not null default 0,
  cache_escritura bigint not null default 0,
  costo_usd       double precision not null default 0,
  detalle         text not null default ''
);
create index if not exists idx_uso_ia_fecha on uso_ia(fecha);
alter table uso_ia enable row level security;

-- Velocidad REAL del sitio público (Core Web Vitals de visitantes reales), la
-- escribe /api/web-vitals con el script de lib/sitio/medicion-velocidad. Se mide
-- acá porque CrUX/Search Console exige más tráfico del que tiene el sitio y
-- PageSpeed solo da laboratorio. Acceso directo por getSupabase() (no datastore).
create table if not exists web_vitals (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  fecha       text not null default '',   -- YYYY-MM-DD (Chile)
  ruta        text not null default '',
  dispositivo text not null default '',   -- movil | escritorio
  fuente      text not null default '',   -- ads | organico
  lcp         double precision,           -- ms
  cls         double precision,
  inp         double precision,           -- ms
  ttfb        double precision            -- ms
);
create index if not exists idx_web_vitals_fecha on web_vitals(fecha);
alter table web_vitals enable row level security;

-- ── Perfiles de acceso (lib/permisos.ts) ────────────────────────────────────
-- Modelo: usuario → perfil → nivel por módulo ('none' | 'ver' | 'editar'), con
-- excepción puntual por persona en `usuario_permisos`. El perfil 'administrador'
-- (el dueño) siempre tiene todo y es el único que entra a Configuración Avanzada.
-- `usuarios.perfil_id` apunta acá (esa columna SÍ está en el mapa SHEETS).
-- Siembra + migración desde `permisos_modulos`: supabase/migracion-perfiles.sql
create table if not exists "perfiles" (
  "id" bigint generated always as identity primary key,
  "slug" text not null unique,
  "nombre" text not null,
  "descripcion" text not null default '',
  "sistema" text not null default 'FALSE',   -- 'TRUE' = perfil base (no se elimina)
  "activo" text not null default 'TRUE',
  "creado_at" timestamptz not null default now()
);
alter table "perfiles" enable row level security;

create table if not exists "perfil_permisos" (
  "perfil_id" bigint not null references "perfiles"("id") on delete cascade,
  "modulo" text not null,
  "nivel" text not null default 'none',      -- none | ver | editar
  "updated_at" text not null default '',
  primary key ("perfil_id", "modulo")
);
alter table "perfil_permisos" enable row level security;

-- Excepción puntual de UNA persona sobre UN módulo; pisa a su perfil.
create table if not exists "usuario_permisos" (
  "usuario_id" text not null,
  "modulo" text not null,
  "nivel" text not null default 'none',
  "updated_at" text not null default '',
  primary key ("usuario_id", "modulo")
);
alter table "usuario_permisos" enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- Parches idempotentes sobre tablas ya creadas (correr sobre una base existente;
-- en una base nueva los CREATE de arriba ya los traen).
-- ─────────────────────────────────────────────────────────────────────────────

-- clientes.video_solicitado (2026-08-02): la solicitud del video del proceso
-- pasa a tener columna propia. Antes se escribía como una línea dentro de
-- `notas`, pero ese campo es SOLO para los comentarios manuales del equipo.
alter table "clientes" add column if not exists "video_solicitado" text not null default '';

-- Migra las solicitudes que quedaron dentro de `notas` y limpia esa línea.
-- Toma la fecha del propio texto ("(DD/MM/YYYY)") y si no se puede leer usa hoy.
update "clientes"
set "video_solicitado" = coalesce(
      to_char(
        to_date(substring("notas" from 'El tutor solicitó el video del proceso \((\d{2}/\d{2}/\d{4})\)'), 'DD/MM/YYYY'),
        'YYYY-MM-DD'),
      to_char(current_date, 'YYYY-MM-DD')),
    "notas" = btrim(regexp_replace("notas", '\n?[^\n]*El tutor solicitó el video[^\n]*', '', 'g'), E' \n')
where "notas" like '%El tutor solicitó el video%';

notify pgrst, 'reload schema';
