-- ════════════════════════════════════════════════════════════════════════════
--  Tablas EXTRA del esquema principal.
--
--  Todo lo de acá NO sale del mapa `SHEETS` (lib/sheets-schema.ts) porque no se
--  accede por `datastore`: son logs y tablas de sistema que usan `getSupabase()`
--  directo. El generador (scripts/generar-schema-sql.ts) las APENDEA al final de
--  supabase/schema-principal.sql — antes vivían pegadas a mano en ese archivo y
--  se PERDÍAN en cada regeneración.
--
--  Al sumar una tabla que no va por datastore, agregarla acá (no al .sql generado).
-- ════════════════════════════════════════════════════════════════════════════

-- Rate limiting de login (NextAuth Credentials, lib/auth.ts vía lib/login-rate-limit.ts):
-- una fila por intento FALLIDO (email+IP). 5 fallidos en 15 min → bloqueado. Fail-open
-- si Supabase falla (un rate limit caído no debe tumbar el acceso).
create table if not exists "login_intentos" (
  "id" bigint generated by default as identity primary key,
  "email" text not null default '',
  "ip" text not null default '',
  "creado_en" text not null default ''
);
alter table "login_intentos" enable row level security;
create index if not exists "login_intentos_email_ip_idx" on "login_intentos" ("email", "ip", "creado_en");
create index if not exists "correos_log_message_id_idx" on "correos_log" ("message_id");

-- Bitácora de decisiones de marketing (lib/marketing-decisiones.ts): registro
-- automático de toda ESCRITURA aprobada que ejecuta el agente (Google Ads: pausas,
-- presupuestos, negativas, RSAs, campañas; Meta: publicar, perfil). Acceso directo
-- por getSupabase() (no datastore), como mailing_logs/correos_log.
create table if not exists marketing_decisiones (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  area        text not null default '',   -- google_ads | meta | contenido
  accion      text not null default '',   -- ej. pausar_campana, presupuesto, negativas_lote, crear_rsa, crear_campana, publicar_pieza
  detalle     text not null default '',   -- qué cambió exactamente (campaña/keyword, antes → después, montos)
  motivo      text not null default '',   -- por qué se hizo (lo aporta el agente al ejecutar)
  resultado   text not null default '',   -- resultado inmediato reportado por la herramienta
  aprobado_por text not null default ''   -- usuario del chat que confirmó la acción
);
create index if not exists idx_mkdec_created on marketing_decisiones(created_at desc);
alter table marketing_decisiones enable row level security;

-- Permisos dinámicos por módulo × rol (editable en Configuración Avanzada → Usuarios).
-- Solo overrides de admin2/operador; lo no listado usa el default de lib/permisos.ts.
create table if not exists "permisos_modulos" (
  "modulo" text not null,
  "rol" text not null,
  "permitido" text not null default 'FALSE',
  "updated_at" text not null default '',
  primary key ("modulo", "rol")
);
alter table "permisos_modulos" enable row level security;

-- Consumo de IA: una fila por llamada a un modelo (Claude) o generación de
-- imagen/video (Gemini). La escribe lib/uso-ia (best-effort) desde cada módulo
-- que consume IA; la lee Configuración Avanzada → Consumo IA. El costo es una
-- ESTIMACIÓN con la tabla de precios de lib/uso-ia, no la factura del proveedor.
-- Acceso directo por getSupabase() (no datastore: es un log, no una entidad).
create table if not exists uso_ia (
  id              bigint generated always as identity primary key,
  created_at      timestamptz not null default now(),
  fecha           text not null default '',   -- YYYY-MM-DD (Chile)
  ts              text not null default '',   -- ISO completo
  modulo          text not null default '',   -- bot-inbox | marketing-chat | imagen | ...
  modelo          text not null default '',
  entrada         bigint not null default 0,  -- input tokens NO cacheados
  salida          bigint not null default 0,
  cache_lectura   bigint not null default 0,
  cache_escritura bigint not null default 0,
  costo_usd       double precision not null default 0,
  detalle         text not null default ''
);
create index if not exists idx_uso_ia_fecha on uso_ia(fecha);
alter table uso_ia enable row level security;

-- Velocidad REAL del sitio público (Core Web Vitals de visitantes reales), la
-- escribe /api/web-vitals con el script de lib/sitio/medicion-velocidad. Se mide
-- acá porque CrUX/Search Console exige más tráfico del que tiene el sitio y
-- PageSpeed solo da laboratorio. Acceso directo por getSupabase() (no datastore).
create table if not exists web_vitals (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  fecha       text not null default '',   -- YYYY-MM-DD (Chile)
  ruta        text not null default '',
  dispositivo text not null default '',   -- movil | escritorio
  fuente      text not null default '',   -- ads | organico
  lcp         double precision,           -- ms
  cls         double precision,
  inp         double precision,           -- ms
  ttfb        double precision            -- ms
);
create index if not exists idx_web_vitals_fecha on web_vitals(fecha);
alter table web_vitals enable row level security;

-- ── Perfiles de acceso (lib/permisos.ts) ────────────────────────────────────
-- Modelo: usuario → perfil → nivel por módulo ('none' | 'ver' | 'editar'), con
-- excepción puntual por persona en `usuario_permisos`. El perfil 'administrador'
-- (el dueño) siempre tiene todo y es el único que entra a Configuración Avanzada.
-- `usuarios.perfil_id` apunta acá (esa columna SÍ está en el mapa SHEETS).
-- Siembra + migración desde `permisos_modulos`: supabase/migracion-perfiles.sql
create table if not exists "perfiles" (
  "id" bigint generated always as identity primary key,
  "slug" text not null unique,
  "nombre" text not null,
  "descripcion" text not null default '',
  "sistema" text not null default 'FALSE',   -- 'TRUE' = perfil base (no se elimina)
  "activo" text not null default 'TRUE',
  "creado_at" timestamptz not null default now()
);
alter table "perfiles" enable row level security;

create table if not exists "perfil_permisos" (
  "perfil_id" bigint not null references "perfiles"("id") on delete cascade,
  "modulo" text not null,
  "nivel" text not null default 'none',      -- none | ver | editar
  "updated_at" text not null default '',
  primary key ("perfil_id", "modulo")
);
alter table "perfil_permisos" enable row level security;

-- Excepción puntual de UNA persona sobre UN módulo; pisa a su perfil.
create table if not exists "usuario_permisos" (
  "usuario_id" text not null,
  "modulo" text not null,
  "nivel" text not null default 'none',
  "updated_at" text not null default '',
  primary key ("usuario_id", "modulo")
);
alter table "usuario_permisos" enable row level security;
