/**
 * Lista canónica de comunas de Chile, agrupadas por región.
 * Usada en el formulario público de inscripción al convenio de eutanasia
 * para que el vet elija en qué comunas atiende, y en el matcher de
 * cotizaciones para validar dirección + comuna.
 *
 * 346 comunas oficiales según División Político-Administrativa (SUBDERE).
 */

export interface ComunaEntry {
  nombre: string
  region: string
}

export const REGIONES = [
  'Arica y Parinacota',
  'Tarapacá',
  'Antofagasta',
  'Atacama',
  'Coquimbo',
  'Valparaíso',
  'Metropolitana',
  "O'Higgins",
  'Maule',
  'Ñuble',
  'Biobío',
  'Araucanía',
  'Los Ríos',
  'Los Lagos',
  'Aysén',
  'Magallanes',
] as const

export const COMUNAS: ComunaEntry[] = [
  // Arica y Parinacota
  { nombre: 'Arica', region: 'Arica y Parinacota' },
  { nombre: 'Camarones', region: 'Arica y Parinacota' },
  { nombre: 'General Lagos', region: 'Arica y Parinacota' },
  { nombre: 'Putre', region: 'Arica y Parinacota' },
  // Tarapacá
  { nombre: 'Alto Hospicio', region: 'Tarapacá' },
  { nombre: 'Camiña', region: 'Tarapacá' },
  { nombre: 'Colchane', region: 'Tarapacá' },
  { nombre: 'Huara', region: 'Tarapacá' },
  { nombre: 'Iquique', region: 'Tarapacá' },
  { nombre: 'Pica', region: 'Tarapacá' },
  { nombre: 'Pozo Almonte', region: 'Tarapacá' },
  // Antofagasta
  { nombre: 'Antofagasta', region: 'Antofagasta' },
  { nombre: 'Calama', region: 'Antofagasta' },
  { nombre: 'María Elena', region: 'Antofagasta' },
  { nombre: 'Mejillones', region: 'Antofagasta' },
  { nombre: 'Ollagüe', region: 'Antofagasta' },
  { nombre: 'San Pedro de Atacama', region: 'Antofagasta' },
  { nombre: 'Sierra Gorda', region: 'Antofagasta' },
  { nombre: 'Taltal', region: 'Antofagasta' },
  { nombre: 'Tocopilla', region: 'Antofagasta' },
  // Atacama
  { nombre: 'Alto del Carmen', region: 'Atacama' },
  { nombre: 'Caldera', region: 'Atacama' },
  { nombre: 'Chañaral', region: 'Atacama' },
  { nombre: 'Copiapó', region: 'Atacama' },
  { nombre: 'Diego de Almagro', region: 'Atacama' },
  { nombre: 'Freirina', region: 'Atacama' },
  { nombre: 'Huasco', region: 'Atacama' },
  { nombre: 'Tierra Amarilla', region: 'Atacama' },
  { nombre: 'Vallenar', region: 'Atacama' },
  // Coquimbo
  { nombre: 'Andacollo', region: 'Coquimbo' },
  { nombre: 'Canela', region: 'Coquimbo' },
  { nombre: 'Combarbalá', region: 'Coquimbo' },
  { nombre: 'Coquimbo', region: 'Coquimbo' },
  { nombre: 'Illapel', region: 'Coquimbo' },
  { nombre: 'La Higuera', region: 'Coquimbo' },
  { nombre: 'La Serena', region: 'Coquimbo' },
  { nombre: 'Los Vilos', region: 'Coquimbo' },
  { nombre: 'Monte Patria', region: 'Coquimbo' },
  { nombre: 'Ovalle', region: 'Coquimbo' },
  { nombre: 'Paiguano', region: 'Coquimbo' },
  { nombre: 'Punitaqui', region: 'Coquimbo' },
  { nombre: 'Río Hurtado', region: 'Coquimbo' },
  { nombre: 'Salamanca', region: 'Coquimbo' },
  { nombre: 'Vicuña', region: 'Coquimbo' },
  // Valparaíso
  { nombre: 'Algarrobo', region: 'Valparaíso' },
  { nombre: 'Cabildo', region: 'Valparaíso' },
  { nombre: 'Calera', region: 'Valparaíso' },
  { nombre: 'Calle Larga', region: 'Valparaíso' },
  { nombre: 'Cartagena', region: 'Valparaíso' },
  { nombre: 'Casablanca', region: 'Valparaíso' },
  { nombre: 'Catemu', region: 'Valparaíso' },
  { nombre: 'Concón', region: 'Valparaíso' },
  { nombre: 'El Quisco', region: 'Valparaíso' },
  { nombre: 'El Tabo', region: 'Valparaíso' },
  { nombre: 'Hijuelas', region: 'Valparaíso' },
  { nombre: 'Isla de Pascua', region: 'Valparaíso' },
  { nombre: 'Juan Fernández', region: 'Valparaíso' },
  { nombre: 'La Cruz', region: 'Valparaíso' },
  { nombre: 'La Ligua', region: 'Valparaíso' },
  { nombre: 'Limache', region: 'Valparaíso' },
  { nombre: 'Llaillay', region: 'Valparaíso' },
  { nombre: 'Los Andes', region: 'Valparaíso' },
  { nombre: 'Nogales', region: 'Valparaíso' },
  { nombre: 'Olmué', region: 'Valparaíso' },
  { nombre: 'Panquehue', region: 'Valparaíso' },
  { nombre: 'Papudo', region: 'Valparaíso' },
  { nombre: 'Petorca', region: 'Valparaíso' },
  { nombre: 'Puchuncaví', region: 'Valparaíso' },
  { nombre: 'Putaendo', region: 'Valparaíso' },
  { nombre: 'Quillota', region: 'Valparaíso' },
  { nombre: 'Quilpué', region: 'Valparaíso' },
  { nombre: 'Quintero', region: 'Valparaíso' },
  { nombre: 'Rinconada', region: 'Valparaíso' },
  { nombre: 'San Antonio', region: 'Valparaíso' },
  { nombre: 'San Esteban', region: 'Valparaíso' },
  { nombre: 'San Felipe', region: 'Valparaíso' },
  { nombre: 'Santa María', region: 'Valparaíso' },
  { nombre: 'Santo Domingo', region: 'Valparaíso' },
  { nombre: 'Valparaíso', region: 'Valparaíso' },
  { nombre: 'Villa Alemana', region: 'Valparaíso' },
  { nombre: 'Viña del Mar', region: 'Valparaíso' },
  { nombre: 'Zapallar', region: 'Valparaíso' },
  // Metropolitana
  { nombre: 'Alhué', region: 'Metropolitana' },
  { nombre: 'Buin', region: 'Metropolitana' },
  { nombre: 'Calera de Tango', region: 'Metropolitana' },
  { nombre: 'Cerrillos', region: 'Metropolitana' },
  { nombre: 'Cerro Navia', region: 'Metropolitana' },
  { nombre: 'Colina', region: 'Metropolitana' },
  { nombre: 'Conchalí', region: 'Metropolitana' },
  { nombre: 'Curacaví', region: 'Metropolitana' },
  { nombre: 'El Bosque', region: 'Metropolitana' },
  { nombre: 'El Monte', region: 'Metropolitana' },
  { nombre: 'Estación Central', region: 'Metropolitana' },
  { nombre: 'Huechuraba', region: 'Metropolitana' },
  { nombre: 'Independencia', region: 'Metropolitana' },
  { nombre: 'Isla de Maipo', region: 'Metropolitana' },
  { nombre: 'La Cisterna', region: 'Metropolitana' },
  { nombre: 'La Florida', region: 'Metropolitana' },
  { nombre: 'La Granja', region: 'Metropolitana' },
  { nombre: 'La Pintana', region: 'Metropolitana' },
  { nombre: 'La Reina', region: 'Metropolitana' },
  { nombre: 'Lampa', region: 'Metropolitana' },
  { nombre: 'Las Condes', region: 'Metropolitana' },
  { nombre: 'Lo Barnechea', region: 'Metropolitana' },
  { nombre: 'Lo Espejo', region: 'Metropolitana' },
  { nombre: 'Lo Prado', region: 'Metropolitana' },
  { nombre: 'Macul', region: 'Metropolitana' },
  { nombre: 'Maipú', region: 'Metropolitana' },
  { nombre: 'María Pinto', region: 'Metropolitana' },
  { nombre: 'Melipilla', region: 'Metropolitana' },
  { nombre: 'Ñuñoa', region: 'Metropolitana' },
  { nombre: 'Padre Hurtado', region: 'Metropolitana' },
  { nombre: 'Paine', region: 'Metropolitana' },
  { nombre: 'Pedro Aguirre Cerda', region: 'Metropolitana' },
  { nombre: 'Peñaflor', region: 'Metropolitana' },
  { nombre: 'Peñalolén', region: 'Metropolitana' },
  { nombre: 'Pirque', region: 'Metropolitana' },
  { nombre: 'Providencia', region: 'Metropolitana' },
  { nombre: 'Pudahuel', region: 'Metropolitana' },
  { nombre: 'Puente Alto', region: 'Metropolitana' },
  { nombre: 'Quilicura', region: 'Metropolitana' },
  { nombre: 'Quinta Normal', region: 'Metropolitana' },
  { nombre: 'Recoleta', region: 'Metropolitana' },
  { nombre: 'Renca', region: 'Metropolitana' },
  { nombre: 'San Bernardo', region: 'Metropolitana' },
  { nombre: 'San Joaquín', region: 'Metropolitana' },
  { nombre: 'San José de Maipo', region: 'Metropolitana' },
  { nombre: 'San Miguel', region: 'Metropolitana' },
  { nombre: 'San Pedro', region: 'Metropolitana' },
  { nombre: 'San Ramón', region: 'Metropolitana' },
  { nombre: 'Santiago', region: 'Metropolitana' },
  { nombre: 'Talagante', region: 'Metropolitana' },
  { nombre: 'Tiltil', region: 'Metropolitana' },
  { nombre: 'Vitacura', region: 'Metropolitana' },
  // O'Higgins
  { nombre: 'Chépica', region: "O'Higgins" },
  { nombre: 'Chimbarongo', region: "O'Higgins" },
  { nombre: 'Codegua', region: "O'Higgins" },
  { nombre: 'Coínco', region: "O'Higgins" },
  { nombre: 'Coltauco', region: "O'Higgins" },
  { nombre: 'Doñihue', region: "O'Higgins" },
  { nombre: 'Graneros', region: "O'Higgins" },
  { nombre: 'La Estrella', region: "O'Higgins" },
  { nombre: 'Las Cabras', region: "O'Higgins" },
  { nombre: 'Litueche', region: "O'Higgins" },
  { nombre: 'Lolol', region: "O'Higgins" },
  { nombre: 'Machalí', region: "O'Higgins" },
  { nombre: 'Malloa', region: "O'Higgins" },
  { nombre: 'Marchigüe', region: "O'Higgins" },
  { nombre: 'Mostazal', region: "O'Higgins" },
  { nombre: 'Nancagua', region: "O'Higgins" },
  { nombre: 'Navidad', region: "O'Higgins" },
  { nombre: 'Olivar', region: "O'Higgins" },
  { nombre: 'Palmilla', region: "O'Higgins" },
  { nombre: 'Paredones', region: "O'Higgins" },
  { nombre: 'Peralillo', region: "O'Higgins" },
  { nombre: 'Peumo', region: "O'Higgins" },
  { nombre: 'Pichidegua', region: "O'Higgins" },
  { nombre: 'Pichilemu', region: "O'Higgins" },
  { nombre: 'Placilla', region: "O'Higgins" },
  { nombre: 'Pumanque', region: "O'Higgins" },
  { nombre: 'Quinta de Tilcoco', region: "O'Higgins" },
  { nombre: 'Rancagua', region: "O'Higgins" },
  { nombre: 'Rengo', region: "O'Higgins" },
  { nombre: 'Requínoa', region: "O'Higgins" },
  { nombre: 'San Fernando', region: "O'Higgins" },
  { nombre: 'San Vicente', region: "O'Higgins" },
  { nombre: 'Santa Cruz', region: "O'Higgins" },
  // Maule
  { nombre: 'Cauquenes', region: 'Maule' },
  { nombre: 'Chanco', region: 'Maule' },
  { nombre: 'Colbún', region: 'Maule' },
  { nombre: 'Constitución', region: 'Maule' },
  { nombre: 'Curepto', region: 'Maule' },
  { nombre: 'Curicó', region: 'Maule' },
  { nombre: 'Empedrado', region: 'Maule' },
  { nombre: 'Hualañé', region: 'Maule' },
  { nombre: 'Licantén', region: 'Maule' },
  { nombre: 'Linares', region: 'Maule' },
  { nombre: 'Longaví', region: 'Maule' },
  { nombre: 'Maule', region: 'Maule' },
  { nombre: 'Molina', region: 'Maule' },
  { nombre: 'Parral', region: 'Maule' },
  { nombre: 'Pelarco', region: 'Maule' },
  { nombre: 'Pelluhue', region: 'Maule' },
  { nombre: 'Pencahue', region: 'Maule' },
  { nombre: 'Rauco', region: 'Maule' },
  { nombre: 'Retiro', region: 'Maule' },
  { nombre: 'Río Claro', region: 'Maule' },
  { nombre: 'Romeral', region: 'Maule' },
  { nombre: 'Sagrada Familia', region: 'Maule' },
  { nombre: 'San Clemente', region: 'Maule' },
  { nombre: 'San Javier', region: 'Maule' },
  { nombre: 'San Rafael', region: 'Maule' },
  { nombre: 'Talca', region: 'Maule' },
  { nombre: 'Teno', region: 'Maule' },
  { nombre: 'Vichuquén', region: 'Maule' },
  { nombre: 'Villa Alegre', region: 'Maule' },
  { nombre: 'Yerbas Buenas', region: 'Maule' },
  // Ñuble
  { nombre: 'Bulnes', region: 'Ñuble' },
  { nombre: 'Chillán', region: 'Ñuble' },
  { nombre: 'Chillán Viejo', region: 'Ñuble' },
  { nombre: 'Cobquecura', region: 'Ñuble' },
  { nombre: 'Coelemu', region: 'Ñuble' },
  { nombre: 'Coihueco', region: 'Ñuble' },
  { nombre: 'El Carmen', region: 'Ñuble' },
  { nombre: 'Ninhue', region: 'Ñuble' },
  { nombre: 'Ñiquén', region: 'Ñuble' },
  { nombre: 'Pemuco', region: 'Ñuble' },
  { nombre: 'Pinto', region: 'Ñuble' },
  { nombre: 'Portezuelo', region: 'Ñuble' },
  { nombre: 'Quillón', region: 'Ñuble' },
  { nombre: 'Quirihue', region: 'Ñuble' },
  { nombre: 'Ránquil', region: 'Ñuble' },
  { nombre: 'San Carlos', region: 'Ñuble' },
  { nombre: 'San Fabián', region: 'Ñuble' },
  { nombre: 'San Ignacio', region: 'Ñuble' },
  { nombre: 'San Nicolás', region: 'Ñuble' },
  { nombre: 'Treguaco', region: 'Ñuble' },
  { nombre: 'Yungay', region: 'Ñuble' },
  // Biobío
  { nombre: 'Alto Biobío', region: 'Biobío' },
  { nombre: 'Antuco', region: 'Biobío' },
  { nombre: 'Arauco', region: 'Biobío' },
  { nombre: 'Cabrero', region: 'Biobío' },
  { nombre: 'Cañete', region: 'Biobío' },
  { nombre: 'Chiguayante', region: 'Biobío' },
  { nombre: 'Concepción', region: 'Biobío' },
  { nombre: 'Contulmo', region: 'Biobío' },
  { nombre: 'Coronel', region: 'Biobío' },
  { nombre: 'Curanilahue', region: 'Biobío' },
  { nombre: 'Florida', region: 'Biobío' },
  { nombre: 'Hualpén', region: 'Biobío' },
  { nombre: 'Hualqui', region: 'Biobío' },
  { nombre: 'Laja', region: 'Biobío' },
  { nombre: 'Lebu', region: 'Biobío' },
  { nombre: 'Los Álamos', region: 'Biobío' },
  { nombre: 'Los Ángeles', region: 'Biobío' },
  { nombre: 'Lota', region: 'Biobío' },
  { nombre: 'Mulchén', region: 'Biobío' },
  { nombre: 'Nacimiento', region: 'Biobío' },
  { nombre: 'Negrete', region: 'Biobío' },
  { nombre: 'Penco', region: 'Biobío' },
  { nombre: 'Quilaco', region: 'Biobío' },
  { nombre: 'Quilleco', region: 'Biobío' },
  { nombre: 'San Pedro de la Paz', region: 'Biobío' },
  { nombre: 'San Rosendo', region: 'Biobío' },
  { nombre: 'Santa Bárbara', region: 'Biobío' },
  { nombre: 'Santa Juana', region: 'Biobío' },
  { nombre: 'Talcahuano', region: 'Biobío' },
  { nombre: 'Tirúa', region: 'Biobío' },
  { nombre: 'Tomé', region: 'Biobío' },
  { nombre: 'Tucapel', region: 'Biobío' },
  { nombre: 'Yumbel', region: 'Biobío' },
  // Araucanía
  { nombre: 'Angol', region: 'Araucanía' },
  { nombre: 'Carahue', region: 'Araucanía' },
  { nombre: 'Cholchol', region: 'Araucanía' },
  { nombre: 'Collipulli', region: 'Araucanía' },
  { nombre: 'Cunco', region: 'Araucanía' },
  { nombre: 'Curacautín', region: 'Araucanía' },
  { nombre: 'Curarrehue', region: 'Araucanía' },
  { nombre: 'Ercilla', region: 'Araucanía' },
  { nombre: 'Freire', region: 'Araucanía' },
  { nombre: 'Galvarino', region: 'Araucanía' },
  { nombre: 'Gorbea', region: 'Araucanía' },
  { nombre: 'Lautaro', region: 'Araucanía' },
  { nombre: 'Loncoche', region: 'Araucanía' },
  { nombre: 'Lonquimay', region: 'Araucanía' },
  { nombre: 'Los Sauces', region: 'Araucanía' },
  { nombre: 'Lumaco', region: 'Araucanía' },
  { nombre: 'Melipeuco', region: 'Araucanía' },
  { nombre: 'Nueva Imperial', region: 'Araucanía' },
  { nombre: 'Padre Las Casas', region: 'Araucanía' },
  { nombre: 'Perquenco', region: 'Araucanía' },
  { nombre: 'Pitrufquén', region: 'Araucanía' },
  { nombre: 'Pucón', region: 'Araucanía' },
  { nombre: 'Purén', region: 'Araucanía' },
  { nombre: 'Renaico', region: 'Araucanía' },
  { nombre: 'Saavedra', region: 'Araucanía' },
  { nombre: 'Temuco', region: 'Araucanía' },
  { nombre: 'Teodoro Schmidt', region: 'Araucanía' },
  { nombre: 'Toltén', region: 'Araucanía' },
  { nombre: 'Traiguén', region: 'Araucanía' },
  { nombre: 'Victoria', region: 'Araucanía' },
  { nombre: 'Vilcún', region: 'Araucanía' },
  { nombre: 'Villarrica', region: 'Araucanía' },
  // Los Ríos
  { nombre: 'Corral', region: 'Los Ríos' },
  { nombre: 'Futrono', region: 'Los Ríos' },
  { nombre: 'La Unión', region: 'Los Ríos' },
  { nombre: 'Lago Ranco', region: 'Los Ríos' },
  { nombre: 'Lanco', region: 'Los Ríos' },
  { nombre: 'Los Lagos', region: 'Los Ríos' },
  { nombre: 'Máfil', region: 'Los Ríos' },
  { nombre: 'Mariquina', region: 'Los Ríos' },
  { nombre: 'Paillaco', region: 'Los Ríos' },
  { nombre: 'Panguipulli', region: 'Los Ríos' },
  { nombre: 'Río Bueno', region: 'Los Ríos' },
  { nombre: 'Valdivia', region: 'Los Ríos' },
  // Los Lagos
  { nombre: 'Ancud', region: 'Los Lagos' },
  { nombre: 'Calbuco', region: 'Los Lagos' },
  { nombre: 'Castro', region: 'Los Lagos' },
  { nombre: 'Chaitén', region: 'Los Lagos' },
  { nombre: 'Chonchi', region: 'Los Lagos' },
  { nombre: 'Cochamó', region: 'Los Lagos' },
  { nombre: 'Curaco de Vélez', region: 'Los Lagos' },
  { nombre: 'Dalcahue', region: 'Los Lagos' },
  { nombre: 'Fresia', region: 'Los Lagos' },
  { nombre: 'Frutillar', region: 'Los Lagos' },
  { nombre: 'Futaleufú', region: 'Los Lagos' },
  { nombre: 'Hualaihué', region: 'Los Lagos' },
  { nombre: 'Llanquihue', region: 'Los Lagos' },
  { nombre: 'Los Muermos', region: 'Los Lagos' },
  { nombre: 'Maullín', region: 'Los Lagos' },
  { nombre: 'Osorno', region: 'Los Lagos' },
  { nombre: 'Palena', region: 'Los Lagos' },
  { nombre: 'Puerto Montt', region: 'Los Lagos' },
  { nombre: 'Puerto Octay', region: 'Los Lagos' },
  { nombre: 'Puerto Varas', region: 'Los Lagos' },
  { nombre: 'Puqueldón', region: 'Los Lagos' },
  { nombre: 'Purranque', region: 'Los Lagos' },
  { nombre: 'Puyehue', region: 'Los Lagos' },
  { nombre: 'Queilén', region: 'Los Lagos' },
  { nombre: 'Quellón', region: 'Los Lagos' },
  { nombre: 'Quemchi', region: 'Los Lagos' },
  { nombre: 'Quinchao', region: 'Los Lagos' },
  { nombre: 'Río Negro', region: 'Los Lagos' },
  { nombre: 'San Juan de la Costa', region: 'Los Lagos' },
  { nombre: 'San Pablo', region: 'Los Lagos' },
  // Aysén
  { nombre: 'Aysén', region: 'Aysén' },
  { nombre: 'Chile Chico', region: 'Aysén' },
  { nombre: 'Cisnes', region: 'Aysén' },
  { nombre: 'Cochrane', region: 'Aysén' },
  { nombre: 'Coyhaique', region: 'Aysén' },
  { nombre: "O'Higgins", region: 'Aysén' },
  { nombre: 'Guaitecas', region: 'Aysén' },
  { nombre: 'Lago Verde', region: 'Aysén' },
  { nombre: 'Río Ibáñez', region: 'Aysén' },
  { nombre: 'Tortel', region: 'Aysén' },
  // Magallanes
  { nombre: 'Antártica', region: 'Magallanes' },
  { nombre: 'Cabo de Hornos', region: 'Magallanes' },
  { nombre: 'Laguna Blanca', region: 'Magallanes' },
  { nombre: 'Natales', region: 'Magallanes' },
  { nombre: 'Porvenir', region: 'Magallanes' },
  { nombre: 'Primavera', region: 'Magallanes' },
  { nombre: 'Punta Arenas', region: 'Magallanes' },
  { nombre: 'Río Verde', region: 'Magallanes' },
  { nombre: 'San Gregorio', region: 'Magallanes' },
  { nombre: 'Timaukel', region: 'Magallanes' },
  { nombre: 'Torres del Paine', region: 'Magallanes' },
]

/** Solo nombres ordenados alfabéticamente. Útil para selects simples. */
export const COMUNAS_NOMBRES: string[] = COMUNAS
  .map(c => c.nombre)
  .sort((a, b) => a.localeCompare(b, 'es'))

/**
 * Nombres de las comunas de la Región Metropolitana (Santiago), en orden
 * alfabético. Usado por el botón "Agregar todas las comunas de Santiago" del
 * formulario de inscripción al convenio de eutanasias.
 */
export const COMUNAS_METROPOLITANA: string[] = COMUNAS
  .filter(c => c.region === 'Metropolitana')
  .map(c => c.nombre)
  .sort((a, b) => a.localeCompare(b, 'es'))

/** Lookup: nombre normalizado → entrada. Para validación al recibir un valor. */
const lookup = new Map<string, ComunaEntry>()
for (const c of COMUNAS) {
  lookup.set(normalizar(c.nombre), c)
}

/** Quita tildes, pasa a minúsculas y trim. */
export function normalizar(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
}

/** Devuelve la entrada canónica si el nombre dado (con/sin tildes) existe. */
export function buscarComuna(nombre: string): ComunaEntry | null {
  if (!nombre) return null
  return lookup.get(normalizar(nombre)) ?? null
}

/** Valida que todos los nombres existan. Devuelve los inválidos. */
export function comunasInvalidas(nombres: string[]): string[] {
  return nombres.filter(n => !buscarComuna(n))
}
