import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { SHEETS } from '../lib/sheets-schema'

/**
 * Genera `supabase/schema-principal.sql` desde el mapa canónico lib/sheets-schema
 * (misma fuente que /api/init-sheets) → incluye TODAS las tablas/columnas, también
 * las creadas en código que aún no se materializaron en la planilla.
 *
 * Decisiones (fase 1 — drop-in seguro):
 *  - Cada tabla: `id bigint generated by default as identity primary key`
 *    (resuelve el race de getNextId con un sequence atómico) + el resto de
 *    columnas como `text default ''` (la app pasa todo como string → máxima
 *    compatibilidad). El tipado fuerte (date/numeric/jsonb) y las FKs quedan
 *    para una fase de hardening posterior, ya sobre Postgres.
 *  - RLS on, sin policies (igual que hoy: solo service_role server-side).
 *  - Función next_id(text) → nextval del sequence de identity (getNextId).
 *
 * Uso:  npx tsx scripts/generar-schema-sql.ts
 */

// Tablas que NO se crean: doc, basura de sync, y mailing_logs (ya vive en el
// proyecto Supabase de mailing con su propio esquema).
const EXCLUIR = new Set(['_README', 'mailing_logs'])
const esConflicto = (n: string) => /_conflict\d+$/i.test(n)

// Índices por columnas que filtramos seguido (solo se crean si la columna existe).
const INDICES: Record<string, string[]> = {
  clientes: ['estado', 'codigo', 'ciclo_id', 'despacho_id', 'veterinaria_id'],
  ciclos: ['fecha'],
  certificados: ['cliente_id'],
  despachos: ['estado_ruta'],
  cotizaciones_eutanasia: ['estado', 'vet_id_asignado'],
  cotizaciones_eutanasia_envios: ['cotizacion_id', 'vet_id'],
  solicitudes_retiro: ['estado', 'cliente_wa_id'],
  mailing_veterinarios: ['email'],
  asistencia: ['fecha'],
  geocoding_cache: ['direccion'],
}

function q(id: string): string { return `"${id.replace(/"/g, '""')}"` }

function main() {

  const out: string[] = []
  out.push('-- Esquema principal (Sheets → Postgres). GENERADO por scripts/generar-schema-sql.ts')
  out.push('-- Correr en el SQL editor del proyecto Supabase de mailing (SUPABASE_URL).')
  out.push('-- Columnas en text (drop-in); id como identity. Ver docs/migracion-postgres.md.\n')

  // Helper getNextId atómico (nextval del sequence de la columna identity).
  out.push(`-- getNextId atómico (reemplaza el max(id)+1 con race de Sheets)`)
  out.push(`create or replace function next_id(p_table text)`)
  out.push(`returns bigint language plpgsql as $$`)
  out.push(`declare seq text; v bigint;`)
  out.push(`begin`)
  out.push(`  seq := pg_get_serial_sequence(p_table, 'id');`)
  out.push(`  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;`)
  out.push(`  execute format('select nextval(%L)', seq) into v;`)
  out.push(`  return v;`)
  out.push(`end $$;\n`)

  // Reset del sequence tras importar ids explícitos (si no, next_id arrancaría en 1).
  out.push(`-- Ajusta el sequence de id al max(id) actual (correr tras el import)`)
  out.push(`create or replace function reset_id_seq(p_table text)`)
  out.push(`returns bigint language plpgsql as $$`)
  out.push(`declare seq text; v bigint;`)
  out.push(`begin`)
  out.push(`  seq := pg_get_serial_sequence(p_table, 'id');`)
  out.push(`  if seq is null then raise exception 'tabla % sin sequence de id', p_table; end if;`)
  out.push(`  execute format('select coalesce(max(id),0) from %I', p_table) into v;`)
  out.push(`  perform setval(seq, greatest(v, 1), v > 0);`)
  out.push(`  return v;`)
  out.push(`end $$;\n`)

  const incluidas: string[] = []
  const excluidas: string[] = []

  for (const [name, columnas] of Object.entries(SHEETS)) {
    if (EXCLUIR.has(name) || esConflicto(name)) { excluidas.push(name); continue }
    const headers = (columnas ?? []).map(h => String(h ?? '').trim()).filter(Boolean)
    if (headers.length === 0) { excluidas.push(`${name} (sin columnas)`); continue }

    // dedupe preservando orden
    const seen = new Set<string>()
    const cols = headers.filter(h => !seen.has(h) && (seen.add(h), true))
    const tieneId = cols.includes('id')
    const otras = cols.filter(c => c !== 'id')

    const lineas: string[] = []
    lineas.push(`  "id" bigint generated by default as identity primary key`)
    for (const c of otras) lineas.push(`  ${q(c)} text not null default ''`)

    out.push(`create table if not exists ${q(name)} (`)
    out.push(lineas.join(',\n'))
    out.push(`);`)
    out.push(`alter table ${q(name)} enable row level security;`)

    for (const col of (INDICES[name] ?? [])) {
      if (cols.includes(col)) {
        out.push(`create index if not exists ${q(`${name}_${col}_idx`)} on ${q(name)} (${q(col)});`)
      }
    }
    out.push('')
    incluidas.push(`${name}${tieneId ? '' : ' (+id surrogate)'}`)
  }

  const sqlPath = join(process.cwd(), 'supabase', 'schema-principal.sql')
  writeFileSync(sqlPath, out.join('\n'), 'utf8')

  console.log(`✅ Esquema generado: supabase/schema-principal.sql`)
  console.log(`   Tablas (${incluidas.length}): ${incluidas.join(', ')}`)
  console.log(`   Excluidas: ${excluidas.join(', ')}`)
  console.log(`   Fuente: lib/sheets-schema.ts`)
}

main()
